### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by frandras** [mzur/gnome-shell-wsmatrix#10]
Hello,
After a recent manjaro update my gnome updated to 3.32.0.
Since the "Workspace grid" extension has been broken (apparently it doesn't work with gnome 3.32), so I uninstall it.
I installed "Workspace Matrix" extension instead, apparently well (I have its dialog windows), but it isn't working.
Can you give me any hint what to do?
Thank you in advance, Andras

**Comment by frandras** [comment]
The problem is that the Super button opens the activities view and somehow its functionality is not overriden (as i suppose it should be).

When I push ALT+CTRL and one of the flashes, the workspace grid appear but disapear a couple of seconds later.

**Comment by mzur** [comment]
You can switch workspaces with Ctrl+Alt+Arrow keys. So to e.g. switch to the workspace to the right, you press Ctrl+Alt+Arrow right. This extension does not have all of the functionality of Workspace Grid and it does not override the Super key or change the display of the workspaces in the activities view.

**Comment by frandras** [comment]
Thank you for your reply! I found annoying that after having pressed "ctrl+alt+arrow" the new view disapears very fast. If you don't press again the arrow in any direction, the view switches back to the normal view.

**Comment by mzur** [comment]
I see. This is the default behavior of GNOME and I didn't want to change that.

**Comment by frandras** [comment]
> I see. This is the default behavior of GNOME and I didn't want to change that.

I can't get to use it. It switches back so fast. It would be really much more user friendly if the other view could stay as long as the user pushes the "ctrl+alt".

**Comment by mzur** [comment]
Can you do a quick video of the behavior? Maybe this is not normal.

**Comment by frandras** [comment]
Hm... it's a bit complicated. I've tried but the result is not good. It blocks in the beginning (the image doesn't change) and at the end is there is something completely bleary.

**Comment by mzur** [comment]
Just for your information: The timeout is [hard coded](https://gitlab.gnome.org/GNOME/gnome-shell/blob/de6512be1a7da4e12748c6980776571bce37a8fd/js/ui/workspaceSwitcherPopup.js#L155) to 600 ms. You would need to override the display function of the workspace switcher popup to change this. I don't plan to update this extension to allow modification of this timeout. But if you want this you could create a fork and implement it yourself.

**Comment by mzur** [comment]
Thanks to an eager contributor the configurable timeout is now implemented and will be available in the next release (see #19).
