### ISSUE TITLE
gnome-tweaks crashing when opening extension settings on Ubuntu 20

### ISSUE THREAD

**Issue by stianlagstad** [mzur/gnome-shell-wsmatrix#102]
Thank you for this extension! When I click the cog wheel here:
![Screenshot from 2020-03-30 09-49-03](https://user-images.githubusercontent.com/4340859/77887925-bb707d00-726b-11ea-81a3-1a42a8e22084.png)
Nothing happens for a few seconds, and then I get this:
![Screenshot from 2020-03-30 09-49-38](https://user-images.githubusercontent.com/4340859/77887960-cb885c80-726b-11ea-91dd-6521eeaf78ca.png)
The details say this:
![Screenshot from 2020-03-30 09-50-46](https://user-images.githubusercontent.com/4340859/77888065-f377c000-726b-11ea-9adc-97e00f8973e1.png)
![Screenshot from 2020-03-30 09-50-51](https://user-images.githubusercontent.com/4340859/77888072-f5418380-726b-11ea-83e5-dcfbdf6cb33c.png)

I'm not sure if this is exclusive to this extension or if the same would happen with other extensions as well. The extension does actually work. I have a 2x3 grid of workspaces now. I'd just like to be able to change that to a 2x2 grid.

Any pointers would be appreciated! Thanks.

**Comment by mzur** [comment]
This looks like you don't have `gnome-shell-extension-prefs` installed which should come included with GNOME. Can you open the preferences of any other extension? I believe that this is no error on the part of this extension.

**Comment by stianlagstad** [comment]
Thanks. `sudo apt install gnome-shell-extension-prefs` fixed the problem.
