### ISSUE TITLE
Setting Path

### ISSUE THREAD

**Issue by jacklu333333** [mzur/gnome-shell-wsmatrix#104]
Hi, 
I accidentally set the workspace number into 36, which overload my PC. Hence, I got no choice but to delete the extension and reinstall it again. From my knowledge, all the extension user setting is in "~/.local/share/gnome-shell/extensions/". Yet, when I remove the whole folder and reinstall again, the extension keep restored my setting, which is 36. I was wondering do I misunderstand or the extension will store the setting in another path. Thanks.
Regards,
Jack Lu

**Comment by mzur** [comment]
Did you resolve your issue? This extension uses the GNOME-level settings for the number of workspaces (`gsettings`) which is unchanged if you uninstall the extension.

**Comment by jacklu333333** [comment]
Hi,
Thank you so much. Sorry for ask such a dumb question. Right after asking it, it occurs to me that the config file and later I found it. I'm a newbie to Linux. Still exploring. Thank you for helping me.

Regards,
Jack Lu
