### ISSUE TITLE
Custom shortcuts don't work on ubuntu

### ISSUE THREAD

**Issue by librowski** [mzur/gnome-shell-wsmatrix#105]
Following the guide from wiki to changing the keyboard shortcuts didn't work for me.
I've tried the set command in multiple way, but it seems it didn't have any effect at all.

**Examplary input:**

```
gsettings --schemadir ~/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/schemas/ set org.gnome.shell.extensions.wsmatrix-keybindings workspace-overview-right "['<Control><Alt>l']"
```

**Distro:** Ubuntu 20.04 (Have tried on 19.10 as well)

**Comment by mzur** [comment]
Do you want to change the shortcut to switch the workspace everywhere (e.g. <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Left</kbd>) or the shortcut to switch the workspace in the overview that is opened with <kbd>Super</kbd>+<kbd>w</kbd>? The shortcut you were setting is only valid for the overview.

**Comment by librowski** [comment]
I see. I'd like to use `h` `j` `k` `l` bindings instead of the arrow keys, so I don't need to switch while working with vim. Is there such possibility?
BTW huge thanks for maintaining this extension. I've been using it for a long time now and it's awesome!

**Comment by ebeem** [comment]
@librowski 
you can get current keybindings for `switch`/`move` to workspace using `gsettings` in terminal
```
$ gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-left                                            
['<Control><Alt>Left']

$ gsettings get org.gnome.desktop.wm.keybindings move-to-workspace-left                                          
['<Control><Shift><Alt>Left']
```

you want to add (maybe replace, but I will provide examples to add) extra keybindings for `h` `j` `k` `l ` 
```
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Control><Alt>Left', '<Control><Alt>H']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Control><Shift><Alt>Left', '<Control><Shift><Alt>H']"
```

you will set new keybindings in gsettings as an array, the above examples show how you can do this task for `switch` and `move` to workspace left

here are all the lines you can run to apply `h` `j` `k` `l ` for both move and switch workspace

```
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Control><Alt>Left', '<Control><Alt>H']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Control><Alt>Right', '<Control><Alt>L']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Control><Alt>Up', '<Control><Alt>K']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Control><Alt>Down', '<Control><Alt>J']"

gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Control><Shift><Alt>Left', '<Control><Shift><Alt>H']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Control><Shift><Alt>Right', '<Control><Shift><Alt>L']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Control><Shift><Alt>Up', '<Control><Shift><Alt>K']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Control><Shift><Alt>Down', '<Control><Shift><Alt>J']"
```

**Comment by mzur** [comment]
As these are default shortcuts of GNOME, you can set them with:
```
gsettings set org.gnome.desktop.wm.keybindings <key> <shortcut>
```
The relevant keys are `switch-to-workspace-up`, `switch-to-workspace-down`, `switch-to-workspace-left` and `switch-to-workspace-right`. There are also `move-to-workspace-*` to move windows. To get all available keys, use:
```
gsettings list-keys org.gnome.desktop.wm.keybindings
```

You can also add the new shortcuts to the existing ones:
```
"['<Control><Alt>Up', '<Control><Alt>k']"
```

**Comment by mzur** [comment]
@ebeem You beat me there :smile:

**Comment by librowski** [comment]
@ebeem @mzur keybindings work like a charm! Thanks for help
