### ISSUE TITLE
Feature request: Indicator in panel

### ISSUE THREAD

**Issue by Archigog** [mzur/gnome-shell-wsmatrix#106]
Hello,

Thanks for the good work ! The extension works like a charm ! :)

Do you plan to add/create-a-new-extension to add an indicator to the panel showing the workspace grid ?

I'm currently using the workspace indicator extension, but it shows the workspaces in one line ...

It would be nice to have something like the workspace grid indicator of XFCE !

Thanks,
Hugo.

**Comment by mzur** [comment]
Sorry but we don't plan to implement such a feature as it is out of scope of this extension. You should ask the workspace indicator developers if they can fix the display for 2D workspaces.
