### ISSUE TITLE
Support to shell 3.4

### ISSUE THREAD

**Issue by BrunoXL** [mzur/gnome-shell-wsmatrix#108]
Hi!!
Do you think about upgrade the extension to support 3.4 gnome shell that comes with Ubuntu 20.04?

**Comment by mzur** [comment]
Ubuntu 20.04 ships with GNOME Shell 3.36 which is supported by this extension. Doesn't it work for you?

**Comment by BrunoXL** [comment]
@mzur I seems I confused things. Just after the installation reboot it didn't worked.
Then I reboot again and now is working fine.
