### ISSUE TITLE
Failed to load in ubuntu 20.04

### ISSUE THREAD

**Issue by adrian-kriegel** [mzur/gnome-shell-wsmatrix#109]
Since upgrading to 20.04 from 19.10, I get the following error: 

> JS ERROR: Extension wsmatrix@martin.zurowietz.de: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
>                                                 Settings@/home/name/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/Settings.js:23:5
>                                                 WsMatrixExtension@/home/name/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:10:22
>                                                 enable@/home/name/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:25:15
> Mai 17 21:45:00 thinkpad-007 gnome-shell[2167]: JS ERROR: Extension wsmatrix@martin.zurowietz.de: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?

**Comment by ebeem** [comment]
make sure you upgrade the extension github/gnome-extensions whenever you upgrade `GNOME`, I think this your problem.

**Comment by adrian-kriegel** [comment]
Thanks, manually installing the extension worked.
