### ISSUE TITLE
this extension is so awesome! (how can i support it?)

### ISSUE THREAD

**Issue by spencer1573** [mzur/gnome-shell-wsmatrix#110]
@mzur, My question is simple: do you have a Patreon or other way i can support this?

**Comment by mzur** [comment]
When people wanted to donate to one of my projects, I've accepted donations through PayPal in the past. However, a significant part of this extension was written by @ebeem so it wouldn't be fair if only I received donations. You could also contribute with code. Just take a look at the open issues with the "help wanted" label

**Comment by spencer1573** [comment]
Thanks!
