### ISSUE TITLE
Feature Request: Thumbnail show all connected monitors, rather than only primary monitor

### ISSUE THREAD

**Issue by chuan-qin** [mzur/gnome-shell-wsmatrix#111]
Currently I am using a laptop connected to another 4k monitor using HDMI. When switching workspaces using shortcut, in the grid/thumbnail matrix, I am only seeing what I have on my primary monitor, but not both monitors, It makes it hard for me to switch to the right workspace swiftly.

Any possibility to support ALL screens?

**Comment by mzur** [comment]
This extension supports a workspace popup for all monitors. You can activate it in the extension settings with the switch "Show popup for all monitors".

**Comment by chuan-qin** [comment]
> This extension supports a workspace popup for all monitors. You can activate it in the extension settings with the switch "Show popup for all monitors".

Thank you @mzur . 	However I failed to find this in the wiki. May I know how to turn on this option? (it s not in extension settings either)
![Screenshot from 2020-06-12 06-27-51](https://user-images.githubusercontent.com/506316/84468422-af933500-ac76-11ea-9a10-4d73e6fd76f1.png)

**Comment by mzur** [comment]
This feature is only available for GNOME Shell 3.32 or newer. You seem to have an older version.

**Comment by chuan-qin** [comment]
> This feature is only available for GNOME Shell 3.32 or newer. You seem to have an older version.

Thank you. Happy to close this issue.
