### ISSUE TITLE
Feature Request: Customizable thickness of "selected" blue border for thumbnails

### ISSUE THREAD

**Issue by chuan-qin** [mzur/gnome-shell-wsmatrix#112]
Currently when I switch workspace, the blue border on selected thumbnail/workspace in matrix is a bit too thin. Prefer to make its thickness customizable.

**Comment by mzur** [comment]
This extension does not control the border width of the workspace indicator. The border width is set by your GNOME Shell theme. You can customize the width by customizing your theme (look for the `workspace-thumbnail-indicator` class).

**Comment by chuan-qin** [comment]
> This extension does not control the border width of the workspace indicator. The border width is set by your GNOME Shell theme. You can customize the width by customizing your theme (look for the `workspace-thumbnail-indicator` class).

Thank you @mzur !
