### ISSUE TITLE
Easier navigation with mouse

### ISSUE THREAD

**Issue by sandorvasas** [mzur/gnome-shell-wsmatrix#113]
This is an awesome extension, which made me possible to switch to Ubuntu 20 from 16. I can't live without a desktop wall, so thanks.

However I use a larger grid and need to quickyl change workspaces many times during the day, and one feature I greatly miss is the navigation using mouse. Would you be able to add a feature that would put an icon on the taskbar (among favorites) which when clicked would act like Super+W and bring up the preview, then the user would be able to click on the desktop to which they want to switch? Moving around with cursors on a 5x5+ grid can be 5+ steps with keyboard, but would be 2 steps with the mouse (click icon, then click target desktop). Would make life much easier.

Many thanks

**Comment by ebeem** [comment]
you can enable grid view in overview from the option `Show workspace grid in the overview`
check this one out.

also, you can assign hotkeys to each gnome workspace, I do that myself, it allows you to move window/switch to any workspace with just one hotkey.

**Comment by mzur** [comment]
I'd say that switching to a workspace using the mouse might be considered as an addition to this extension. An icon in the taskbar rather not as there already is the [workspace indicator](https://extensions.gnome.org/extension/21/workspace-indicator/) extension. @sandorvasas maybe workspace indicator is a solution for you, too, as it allows to switch to a workspace with a click. No need to bloat this extension then.

**Comment by mzur** [comment]
Please reopen if this is still relevant.
