### ISSUE TITLE
Gnome 3.36.3: JS ERROR: Extension wsmatrix@martin.zurowietz.de: TypeError: Main.overview._overview is undefined

### ISSUE THREAD

**Issue by Quip11** [mzur/gnome-shell-wsmatrix#114]
```
JS ERROR: Extension wsmatrix@martin.zurowietz.de: TypeError: Main.overview._overview is undefined
                                                            _activateOverride@/home/dennisf/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js:78:31
                                                            _handleShowOverviewGridChanged@/home/dennisf/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js:68:15
                                                            OverviewOverride@/home/dennisf/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js:21:12
                                                            WsMatrixExtension@/home/dennisf/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:13:31
                                                            enable@/home/dennisf/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:25:15
                                                            _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                                            loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:348:26
                                                            activate@/home/dennisf/.local/share/gnome-shell/extensions/extension-reloader@nls1729/extension.js:117:34
                                                            vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:138:14
```

**Comment by ebeem** [comment]
please make sure you are using the latest version of the extension

**Comment by Quip11** [comment]
I just cloned the repo.

**Comment by ebeem** [comment]
sorry for being late
I too use gnome 3.36.3, this error shouldn't occur.

try running this command in the `gnome-shell` `looking-glass` (press alt+F2, then type lg)
```
imports.ui.main.overview._overview
```

the output should be something other than undefined. According to the error, the output is undefined,
if that's the case, then either your gnome-shell is extremely modified or you're installing an extension that replaces the overview somehow.

**Comment by Quip11** [comment]
It says **undefined**.

I'm running Gnome in Classic mode.  It still has an overview, although Classic's overview doesn't show the thumbnails of screens, just the windows.

Gnome in Standard mode crashes.

**Comment by ebeem** [comment]
I don't think anybody tested this extension on gnome-classic before.
So it could actually be the reason why you're receiving this error.

I will try to check it out once I have time and let you know how it goes.

**Comment by Quip11** [comment]
FWIW, in my local copy I removed the four lines requiring Main.overview._overview and the extension no longer crashes:
```
diff --git a/wsmatrix@martin.zurowietz.de/OverviewOverride.js b/wsmatrix@martin.zurowietz.de/OverviewOverride.js
index 71ddc02..c042c51 100644
--- a/wsmatrix@martin.zurowietz.de/OverviewOverride.js
+++ b/wsmatrix@martin.zurowietz.de/OverviewOverride.js
@@ -75,10 +75,6 @@ var OverviewOverride = class {
 
    _activateOverride() {
       this._overrideActive = true;
-      let workspacesDisplay = Main.overview._overview._controls.viewSelector._workspacesDisplay;
-      this._workspacesDisplayOverride = new WorkspacesDisplayOverride(workspacesDisplay);
-      let thumbnailsBox = Main.overview._overview._controls._thumbnailsBox;
-      this._thumbnailsBoxOverride = new ThumbnailsBoxOverride(thumbnailsBox, this.rows, this.columns);
       this._workspacesViewOverride = new WorkspacesViewOverride(this.settings);
    }
```

**Comment by Quip11** [comment]
Oh, and I removed the corresponding cleanup lines from _deactivateOverride() too.

**Comment by ebeem** [comment]
Thanks for your feedback, I am not sure if this issue is part of the extension's scope, so I will leave this to @mzur to decide.

**Comment by mzur** [comment]
If this is everything that's required to be compatible with GNOME Classic then I think it's reasonable to disable the OverviewOverride altogether if `_overview` is undefined ([here](https://github.com/mzur/gnome-shell-wsmatrix/blob/0a6bd59823fe8fde8df12aa46da6497f76443158/wsmatrix%40martin.zurowietz.de/extension.js#L13)). @ebeem Do you agree?

@Quip11 Or do you still need the WorkspacesViewOverride for the GNOME Classic overview?

**Comment by Quip11** [comment]
@mzur I don't see a diff at your link.

No, I doubt Classic would need workspacesViewOverride.  Disable the OverviewOverride altogether if _overview is undefined.

**Comment by mzur** [comment]
@Quip11 Please try the `gnome-classic` branch and report if this works for you without errors.

**Comment by Quip11** [comment]
Thank you.  It works on Gnome Classic without errors.
