### ISSUE TITLE
bug: the window in non primary monitor doesn't move

### ISSUE THREAD

**Issue by cyberhck** [mzur/gnome-shell-wsmatrix#115]
So when I do Shift + Ctrl + Arrow keys to move a window around so I can organize, if there's a app on second monitor, it doesn't move, no matter what workspace I'm on, it's always there and can't move it to separate workspace,

Let me know if you need more info (I'm on fresh installation of Ubuntu 20.04 LTS)

**Comment by ebeem** [comment]
make sure in `gnome tweaks` you have this option enabled under display handling (**Workpaces span displays**)
![Screenshot from 2020-07-05 19-11-05](https://user-images.githubusercontent.com/25146039/86536817-4d36f880-bef3-11ea-87b2-27000e6c05df.png)

**Comment by cyberhck** [comment]
thanks a lot, that works, though I used the following command:
```bash
gsettings set org.gnome.mutter workspaces-only-on-primary false
```
putting it here in case someone else stumbles across this, (didn't want to install the tweak tool)
