### ISSUE TITLE
Feature request: configurable shortcuts to scroll past empty workspaces

### ISSUE THREAD

**Issue by peey** [mzur/gnome-shell-wsmatrix#116]
Suppose that you have the following matrix:

```
o | - | o | -
o | - | o | -
```

Where `o` is a workspace occupied by one or more windows, and `-` is an un-occupied workspace. I'll give them numbers so it's easy to talk about them:

```
1 | 2 | 3 | 4
5 | 6 | 7 | 8
```

I'd like to have two "move to the right workspace" behaviours, one that takes me from 1 to 2 as usual, and another that'd take me from 1 to 3, effectively skipping the empty workspaces.

I can attach a custom shortcut for this skipping behaviour so it doesn't break compatibility with existing behaviour and users

**Comment by ebeem** [comment]
try `dcon editor` if you want an interface to change the shortcuts.
`GNOME` allows you to control shortcuts (this includes the shortcuts used in this extension)

the paths of the shortcuts are (where X is the number of the workspace)
`/org/gnome/desktop/wm/keybindings/move-to-workspace-X` `(moves window to workspace#X)`
`/org/gnome/desktop/wm/keybindings/switch-to-workspace-X` `(switches workspace to workspace#X)`

You will need to think about what shortcuts make more sense to you, the shortcuts that I use are the keypads 1-9, this makes so much more sense to me as I use a 3x3 matrix, Here are my configurations to assign shortcuts using the `gsettings` interface in the terminal, This will allow me to 
1- switch to a workspace number using `<Primary><Alt><KeyPadButton>` 
1- move window to a workspace number using `<Primary><Alt><KeyPadButton>` 

Note that my configuration remaps workspaces `1-3` to keypads `7-9` and workspaces `7-9` to keypads `1-3`, the reason behind this is to allow me to navigate the gird easier as it makes the keypads and the matrix share the same workspace arrangement.

if you want to keep your current matrix (2x4) then I recommend that you reassign the shortcuts that I have below as they won't work well for your case.

You can re-assign shortcuts as you want.

```
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Primary><Alt>KP_7']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Primary><Alt>KP_8']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Primary><Alt>KP_9']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Primary><Alt>KP_4']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Primary><Alt>KP_5']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Primary><Alt>KP_6']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 "['<Primary><Alt>KP_1']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8 "['<Primary><Alt>KP_2']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9 "['<Primary><Alt>KP_3']" 

gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Primary><shift><Alt>KP_7']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Primary><shift><Alt>KP_8']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Primary><shift><Alt>KP_9']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Primary><shift><Alt>KP_4']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 "['<Primary><shift><Alt>KP_5']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 "['<Primary><shift><Alt>KP_6']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-7 "['<Primary><shift><Alt>KP_1']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-8 "['<Primary><shift><Alt>KP_2']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-9 "['<Primary><shift><Alt>KP_3']" 
```

**Comment by peey** [comment]
Thanks, I know how to re-assign shortcuts. But I don't know how to detect what's the next non-empty workspace in a direction (left, right, top, bottom).

I'm guessing that has to be done within application logic of the app.

**Comment by mzur** [comment]
Sorry but I'd consider this out of scope of this extension. The primary focus is to enable a 2D grid of workspaces. Maybe this feature can be implemented in a separate extension and made compatible with 2D workspace arrangements.

**Comment by peey** [comment]
@mzur that's acceptable, thanks!

I don't want to give the maintainers more burden than they want for feature-requests, but would you be able to accept a PR or point me in the right direction toward implementing this?

I have two questions:

1. https://github.com/mzur/gnome-shell-wsmatrix/blob/master/wsmatrix%40martin.zurowietz.de/WmOverride.js#L424 seems to be the line of interest to me. If I can check within `get_neigbhor` what's the next non-empty workspace in a direction and return it, then rest of the code should remain unchanged. Is that right?
2. Do you manage the workspaces in a datastructure local to your extension or is the data structure accessible outside of your extension? In the latter case, I suppose implementation as a separate extension would be as easy as implementation within this extension.

**Comment by mzur** [comment]
I admit that it's probably easier to implement the feature in this extension. A separate extension would likely be incompatible with this one. If your PR does not add too much code/complexity I'll probably accept it. My only concern is that this extension gets so much features that it gets too hard and time comsuming to maintain it and establish compatibility with newer GNOME versions (which tend to break things).

As to your questions: The `_getTargetWorkspace` function you pointed to is probably the best location to implement such a feature. The `get_neighbor` function cannot be modified by an extension as far as I can tell. The workspace object should even have an [`isEmpty`](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/0893789b34419a944e5b44e83ea52766bbb3db97/js/ui/workspace.js#L874-876) function that you can use.

**Comment by peey** [comment]
Thanks for your response! 

I think if I'm diving into writing code, I might as well write a few other features I wish to have. And I'm not sure if this is a feature that someone other than me would be interested in either.

So I think it may better belong in a personal fork or a separate project altogether. I'm going to close this issue for now.
