### ISSUE TITLE
not working on ubuntu 20

### ISSUE THREAD

**Issue by ussamazahid96** [mzur/gnome-shell-wsmatrix#120]
output of the command `journalctl /usr/bin/gnome-shell` from the time after I installing and restarting with Alt+F2 and r.

`Aug 23 17:07:55 uzahid-Inspiron-3542 gnome-shell[1985]: JS WARNING: [resource:///org/gnome/shell/misc/extensionUtils.js 217]: reference to undefined property "metadata"
Aug 23 17:09:19 uzahid-Inspiron-3542 gnome-shell[1985]: Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
Aug 23 17:09:19 uzahid-Inspiron-3542 gnome-shell[1985]: Object Meta.BackgroundActor (0x5607faab6f20), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Aug 23 17:09:19 uzahid-Inspiron-3542 gnome-shell[1985]: == Stack trace for context 0x5607f9623700 ==
Aug 23 17:09:19 uzahid-Inspiron-3542 gnome-shell[1985]: #0   7ffd78d37f40 b   resource:///org/gnome/gjs/modules/core/overrides/GObject.js:571 (27485cbb6c40 @ 25)
Aug 23 17:09:19 uzahid-Inspiron-3542 gnome-shell[1985]: #1   5607f98548b8 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:209 (3f097189f088 @ 85)
Aug 23 17:09:19 uzahid-Inspiron-3542 gnome-shell[1985]: #2   5607f9854830 i   /usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:148 (3f0971898e20 @ 12)
Aug 23 17:09:19 uzahid-Inspiron-3542 gnome-shell[1985]: #3   5607f98547a8 i   resource:///org/gnome/shell/ui/main.js:236 (27485cbd5e98 @ 12)
Aug 23 17:09:19 uzahid-Inspiron-3542 gnome-shell[1985]: JS ERROR: Error: Argument 'instance' (type interface) may not be null
                                                        _init/GObject.Object.prototype.disconnect@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:571:24
                                                        _onDestroy@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:209:45
                                                        _init/<@/usr/share/gnome-shell/extensions/desktop-icons@csoriano/desktopGrid.js:148:44
                                                        _initializeUI/<@resource:///org/gnome/shell/ui/main.js:236:16
Aug 23 17:09:19 uzahid-Inspiron-3542 gnome-shell[1985]: JS ERROR: TypeError: actor.get_meta_window(...) is null
                                                        _destroyWindowDone@resource:///org/gnome/shell/ui/windowManager.js:1590:32
                                                        onStopped@resource:///org/gnome/shell/ui/windowManager.js:1560:39
                                                        _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:73:13
                                                        _easeActor/<@resource:///org/gnome/shell/ui/environment.js:149:56
                                                        _initializeUI/<@resource:///org/gnome/shell/ui/main.js:236:16
Aug 23 17:09:20 uzahid-Inspiron-3542 gnome-shell[1985]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug 23 17:09:20 uzahid-Inspiron-3542 gnome-shell[1985]: Will monitor session 2
Aug 23 17:09:21 uzahid-Inspiron-3542 gnome-shell[1985]: Telepathy is not available, chat integration will be disabled.
Aug 23 17:09:22 uzahid-Inspiron-3542 gnome-shell[1985]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug 23 17:09:23 uzahid-Inspiron-3542 gnome-shell[1985]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Aug 23 17:09:23 uzahid-Inspiron-3542 gnome-shell[1985]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Aug 23 17:09:23 uzahid-Inspiron-3542 gnome-shell[1985]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
Aug 23 17:09:23 uzahid-Inspiron-3542 gnome-shell[1985]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Aug 23 17:09:23 uzahid-Inspiron-3542 gnome-shell[1985]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Aug 23 17:09:23 uzahid-Inspiron-3542 gnome-shell[1985]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Aug 23 17:09:23 uzahid-Inspiron-3542 gnome-shell[1985]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Aug 23 17:09:23 uzahid-Inspiron-3542 gnome-shell[1985]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Aug 23 17:09:23 uzahid-Inspiron-3542 gnome-shell[1985]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Aug 23 17:09:23 uzahid-Inspiron-3542 gnome-shell[1985]: GNOME Shell started at Sun Aug 23 2020 17:09:21 GMT+0100 (IST)
Aug 23 17:09:23 uzahid-Inspiron-3542 gnome-shell[1985]: Registering session with GDM
` 

any idea why it isn't working?

**Comment by ebeem** [comment]
this seems like a bug with `desktop-icons`, are you sure `wsmatrix` is not working?

**Comment by mzur** [comment]
Please reopen if this is still relevant.
