### ISSUE TITLE
Issue with shortcuts Ctrl-Alt-[Left/Right/Top/Down]

### ISSUE THREAD

**Issue by paugier** [mzur/gnome-shell-wsmatrix#121]
On my computer (Gnome 3.30, Debian 10), the shortcuts are buggy:

- Ctrl-Alt-Right and Ctrl-Alt-Left do nothing
- Ctrl-Alt-Down moves towards the right
- Ctrl-Alt-Top moves towards the left

Same in the workspace-overview.

However, the command
```
gsettings --schemadir ~/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/schemas/ \
   get org.gnome.shell.extensions.wsmatrix-keybindings workspace-overview-right
```
gives the correct default value `['Right']`.

What can be done / tried?

**Comment by mzur** [comment]
Please have a look at #74. I mentioned a bug in Mutter there which could explain your issues.

**Comment by paugier** [comment]
Thank for the answer and sorry to disturb you with a known issue! Maybe it is worth to write a warning in the README or/and in the description of the extension about this issue.

It is understood and solved upstream but it continues to affect all Debian 10 users.

**Comment by mzur** [comment]
Sounds reasonable. Care to propose an addition to the "Known Issues / FAQ" section of the readme?

**Comment by paugier** [comment]
> Care to propose an addition to the "Known Issues / FAQ" section of the readme?

Ok. I'll do that.
