### ISSUE TITLE
Problems when "Horizontal Workspaces" extension is enabled

### ISSUE THREAD

**Issue by set-soft** [mzur/gnome-shell-wsmatrix#122]
Not real issues, just notes in case somebody has the same problems:

I had it enabled and it prevented wsmatrix from showing in the overview.

Also: after disabling "Horizontal Workspaces" I had to restart GNOME because the order of workspaces in wsmatrix became "interlaced".

**Comment by mzur** [comment]
Thanks for noting this. I don't think anything can be done about this because both extensions modify the workspace behavior and can't be compatible with each other. I'm closing this issue. Please reopen if there is anything else.
