### ISSUE TITLE
Switcher without thumbnails changes size

### ISSUE THREAD

**Issue by mzur** [mzur/gnome-shell-wsmatrix#126]
If thumbnails are disabled, the workspace switcher is bigger on the first two workspaces than on the remaining workspaces ([ref](https://github.com/mzur/gnome-shell-wsmatrix/issues/123#issuecomment-704429748)).

**Comment by mzur** [comment]
The size is now constant but the popup position still changes as if the size would be changing like before. Couldnt find out why. Similar to what was described in #14.

**Comment by ebeem** [comment]
I did a very quick check. I think mainly what fixed this issue with the thumbnails was caching.
I tried that very quickly and it worked, but I need to test it more.

**Comment by ebeem** [comment]
implemented and tested in #152, please let's discuss any issue with the current implementation (if any) in the PR.
