### ISSUE TITLE
Scrolling in the vertical workspace list in the overview does not work correctly

### ISSUE THREAD

**Issue by mzur** [mzur/gnome-shell-wsmatrix#127]
If the workspace grid is not enabled in the overview, scrolling does not cycle through all workspaces but only through the ones in the first column.

**Comment by cidevant** [comment]
+1

**Comment by ebeem** [comment]
We will need to always override the `_onScrollEvent` in `workspacesDisplay` regardless whether the overview is enabled or not.

**Comment by ebeem** [comment]
fixed in #152 6ae77b2
