### ISSUE TITLE
Windows collapse into a single workspace after suspend

### ISSUE THREAD

**Issue by gotjen** [mzur/gnome-shell-wsmatrix#128]
Ubuntu 20.08 LTS, ASUS Zenbook, HDMI external monitor.

When I'm working with windows in multiple workspaces and suspend, all the windows collapse into a single workspace. I'm normally working in a 60% split ratio - everything lands in the same window with the most recently used application at the end of the toolbar. It costs a lot of time to move all the windows back to a usable configuration before I can get back to projects. The same happens whether I'm on two screens, just the external or just my laptop.

To reproduce, set up windows in multiple workspaces
After suspend and wake, windows appear in the same workspace.

example before suspend:
![image](https://user-images.githubusercontent.com/372588/95679795-34e61200-0ba3-11eb-8ada-d1c00842518e.png)

example after suspend:
![image](https://user-images.githubusercontent.com/372588/95680223-09185b80-0ba6-11eb-941f-a2ab0aa44981.png)

**Comment by gotjen** [comment]
My mistake, I'm using material shell. Wrong repo?

**Comment by mzur** [comment]
Please have a look at the [FAQ](https://github.com/mzur/gnome-shell-wsmatrix#known-issues--faq). Try to disable the extension, set workspaces to "static" in GNOME Tweaks and then enable this extension again.

**Comment by mzur** [comment]
Please reopen if this is still relevant.
