### ISSUE TITLE
Center the workspace grid in overview

### ISSUE THREAD

**Issue by danogh** [mzur/gnome-shell-wsmatrix#129]
Would it be possible to vertically center the workspace grid in the overview?   This applies when "Show workspace gird in the overview" is on.

Thanks!

**Comment by mzur** [comment]
Thanks for your interest in this extension. What you propose might be possible but I'd rather stick to the default behavior of GNOME here. I don't want this extension to become more complex. Feel free to implement this change in a fork.

**Comment by mzur** [comment]
Please reopen if this is still relevant.
