### ISSUE TITLE
No matrix in 20.10

### ISSUE THREAD

**Issue by richardquint** [mzur/gnome-shell-wsmatrix#130]
In two installations of 20.10 (one an upgrade, the other a fresh install) instead of the 2x2 grid expected I just get a single column with 4 rows. The entry for Workspace Matrix on https://extensions.gnome.org/local/ shows Error.  Reinstalling and rebooting have no effect.

**Comment by mzur** [comment]
Please look for errors in `journalctl /usr/bin/gnome-shell` and post them here.

**Comment by richardquint** [comment]
Oct 25 09:09:11 Nineteen10 gnome-shell[1149]: JS ERROR: Extension wsmatrix@martin.zurowietz.de: TypeError: this.workspacesDisplay[prop] is undefined
                                              overrideOriginalProperties/<@/home/rquint/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/WorkspacesDisplayOverride.js:23:10
                                              overrideOriginalProperties@/home/rquint/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/WorkspacesDisplayOverride.js:22:31
                                              WorkspacesDisplayOverride@/home/rquint/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/WorkspacesDisplayOverride.js:13:12
                                              _activateOverride@/home/rquint/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js:79:41
                                              _handleShowOverviewGridChanged@/home/rquint/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js:68:15
                                              OverviewOverride@/home/rquint/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js:21:12
                                              WsMatrixExtension@/home/rquint/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:15:34
                                              enable@/home/rquint/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:30:15

**Comment by mzur** [comment]
This looks like the issues reported in #123. They should be fixed with v5-beta. You are welcome to help finish up the PR for v5 with GNOME 3.38 support in #125 .
