### ISSUE TITLE
Changed behaviour switching between workspaces 

### ISSUE THREAD

**Issue by fnog** [mzur/gnome-shell-wsmatrix#131]
Hi there.

After upgrading ubuntu to 20.10, the way the switching between workspaces changed.

For example, on a 2x2 layout, before 20.10, if I switched "right" multiple times, it would end up on the rightmost workspace while, now, it jumps from the rightmost to the leftmost.

The available settings, while a little different, don't seem to do the trick. Am I missing anything?

BTW, great extension. Love it.

**Comment by mzur** [comment]
Please check in the extension settings if the "Wraparound mode" is set to `None`.

**Comment by mzur** [comment]
Please reopen if this is still relevant.

**Comment by fnog** [comment]
Not sure if you changed anything but after updating the extension just now, it's working again as before (haven't changed anything).

Few! What a relief! Since I no longer can live without your extension, it was simply destroying my ubuntu workflow...
Kudos!

**Comment by mzur** [comment]
If you want to support this extension, consider a contribution to the GNOME 3.38 PR #125 :wink:
