### ISSUE TITLE
Extension says error, restarting doesn't help

### ISSUE THREAD

**Issue by Ulrar** [mzur/gnome-shell-wsmatrix#132]
Hi,

I've just updated my system and the extension now just says error. It seems to still be creating the number of workspace, but not arranging them as it should. I've tried restarting multiple times, and also re-installing the extension, no difference.
Is there some log file I need to check to figure out what's going on ?

Thanks

**Comment by mzur** [comment]
Have you updated to GNOME 3.38? Try to install v5-beta of this extension. Also have a look at #125.

**Comment by mzur** [comment]
Please reopen if this is still relevant.
