### ISSUE TITLE
this.workspacesDisplay[prop] is undefined

### ISSUE THREAD

**Issue by kstolcenberg** [mzur/gnome-shell-wsmatrix#134]
I've been getting this error ever since upgrading to 3.38. I'm using pop!_os. 

I see that this is defined in WorkspacesDisplayOverride.js, but I don't know enough javascript to figure out why my machine isn't parsing it correctly.

**Comment by mzur** [comment]
Please have a look at #125 for GNOME 3.38 support. v5-beta of this extension fixes some of the issues.
