### ISSUE TITLE
Feature request: multi-monitor support in workspace thumbnails

### ISSUE THREAD

**Issue by PeterJCLaw** [mzur/gnome-shell-wsmatrix#137]
Thanks for this great extension. It's really useful to be able to lay out workspaces in more than one dimension!

I have a multi-monitor (two) setup and I'd like to be able to see all the windows I have open when I switch between workspaces. At the moment I end up overlooking that I already have a window open somewhere because the thumbnails only include the windows from the primary monitor.

I've already used the Tweaks tool to configure the workspaces to span displays, so I do have separate windows on each workspace, it's just that they aren't easily shown.

Is this something you're able to support? (Am I missing a setting somewhere?)

**Comment by ebeem** [comment]
can you try the `Show popup for all monitors` option? I think it's what you're looking for
![Screenshot from 2020-12-02 23-31-25](https://user-images.githubusercontent.com/25146039/100927871-87361600-34f6-11eb-956f-87caff78d40e.png)

**Comment by PeterJCLaw** [comment]
Aha, I see. I had spotted that, but hadn't noticed it doing anything. Now I see what it does.

I think that gets part of the way there, but not entirely -- you'd need to look at all your monitors at once in order to see each of the windows.

I was hoping that the solution would show the whole workspace as a single thumbnail (side by side), rather than as two or more split parts.

For context: I'm moving over to Gnome Shell from having been used to a Gnome Flashback based configuration, which did show the whole workspace as a single thumbnail.

**Comment by mzur** [comment]
This is not easily implemented, I'm afraid. As we are already struggling with even the basic GNOME 3.38 support, there is no one here to implement this (unless you want to do it yourself).

**Comment by mzur** [comment]
Please reopen if anyone is willing to work on this.
