### ISSUE TITLE
Switcher doesn't interop with walkpaper's per-workspace backgrounds

### ISSUE THREAD

**Issue by qwitwa** [mzur/gnome-shell-wsmatrix#139]
I've set up 16 workspaces in a 4x4 grid and set each of them to show a fragment of a large image using [walkpaper](https://extensions.gnome.org/extension/1200/walkpaper/). Unfortunately this isn't represented in the preview I see when switching, presumably because that extension is directly mutating the desktop state to achieve that effect. Is there any way this extension could detect when walkpaper was installed and make use of that in the popup? 

![Screenshot from 2021-01-09 01-52-13](https://user-images.githubusercontent.com/2302478/104080511-57c6a780-5220-11eb-868a-b3a4dfad6d31.png)

**Comment by mzur** [comment]
It might be possible but I don't plan to add support for other extensions here. This extension uses the default workspace thumbnails of GNOME for the popup (the ones from the activity overview). Maybe this can be fixed on the part of walkpaper or you can fork this extension.

**Comment by qwitwa** [comment]
Yeah, that's fair. Thanks for the quick response!
