### ISSUE TITLE
Workspace popup jumps

### ISSUE THREAD

**Issue by weeman1337** [mzur/gnome-shell-wsmatrix#14]
The workspace popup jumps when doing the second action.

Reproduction steps:
- Move to another workspace
- Move to another workspace again before the popup closes

Expected:
- The popup keeps the same position

What happens:
- The popup changes it's position

See the video: https://framadrop.org/r/z6aln6k1Ua#n0LFHOCGPFL9jm2MKa4KE3kxxBkamNU8nIYJiW81ltc=

I found out that `y` is different because `containerNatHeight` changed here: https://github.com/mzur/gnome-shell-wsmatrix/blob/master/wsmatrix%40martin.zurowietz.de/WorkspaceSwitcherPopup.js#L144

It doesn't jump for the 3rd, 4th ... action.

**Comment by mzur** [comment]
Can you check if this happens for the default workspace switcher popup, too? The part you pointed out [has not been changed](https://gitlab.gnome.org/GNOME/gnome-shell/blob/4d4d5a0b160e0f3990ed98a08875e442a4a0f191/js/ui/workspaceSwitcherPopup.js#L131-135).

**Comment by weeman1337** [comment]
@mzur thanks for the fast response.
If you mean the default GNOME switcher: It doesn't jump.

**Comment by weeman1337** [comment]
I looked at the standard switcher code. As mentioned in the issue description I think it jumps because the container height changes on the second calculation.

The code inside `_redisplay` is fine.

**Comment by tom-james-watson** [comment]
I was about to report the same issue - it has always done this for me too.

**Comment by mzur** [comment]
I can confirm this with a fresh install of Ubuntu 19.04. Strange that this doesn't happen with Ubuntu 18.04 which I'm currently using. Must be something with the new GNOME version and v2 of this extension.

**Comment by ebeem** [comment]
I had this issue too, my workaround isn't perfect
I noticed the change in `_itemSpacing` but I couldn't realize why it's happening
so in the constructor, I copied the initial `_itemSpacing` into a new variable and used it instead of the inherited `_itemSpacing`

```
   _init(rows, columns, scale) {
      super._init();
      this._rows = rows;
      this._columns = columns;
      this._scale = scale;
      this._activeWorkspaceIndex = 0;
      this._itemSpacingFixed = this._itemSpacing;
   }
```

I will open a pull request soon
