### ISSUE TITLE
Labels are very small

### ISSUE THREAD

**Issue by toobaz** [mzur/gnome-shell-wsmatrix#140]
First, thanks for this great extension.

Unfortunately, in the popup labels (when enabled) are very small:

![Schermata da 2021-01-14 08-13-59](https://user-images.githubusercontent.com/1224492/104557230-2e06e980-5641-11eb-92ea-cbf2b8f73a3f.png)

I didn't find a way to rescale them.

(gnome-shell 3.38.2-1 in Debian testing)

(By the way: it would be great to be able to show both the preview AND the label - related to #41 )

**Comment by mzur** [comment]
The label font size should be more or less the same than the text in the panel at the top. Is this too small for you, too? Maybe this is a GNOME 3.38 issue (which is still not fully supported by this extension #125). You could change the font size with your theme and the `.ws-switcher-label` selector. Or you would have to implement a new settings option for this extension which applies a new `style: 'font-size: XXpx;'` [here](https://github.com/mzur/gnome-shell-wsmatrix/blob/16609ff92e8c512e570fa3ed528357912a911546/wsmatrix%40martin.zurowietz.de/IndicatorWsmatrixPopup.js#L118-L121).

**Comment by toobaz** [comment]
> The label font size should be more or less the same than the text in the panel at the top. Is this too small for you, too?

I confirm they look the same size... which seems small to me. Maybe because I'm used to Workspace-Grid, where they would take most of the available empty space, making them easier to quickly look up:
https://www.worldofgnome.org/workspace-grid-shell-extension-for-gnome-3-8

My opinion would be that since the label is shown in an empty box, nobody will complain if you just make the label fill more of that box, so I wouldn't see a new setting option as needed.

I did not understand - but I will investigate - your suggestion of using the ``.ws-switcher-label`` selector.

**Comment by mzur** [comment]
I agree that the label display could be improved. At least the labels could be centered in the workspace indicators. But when you say "make the label fill more of that box", how to determine the size? Should the label fill the whole width of the indicator? This would produce different sizes for different labels which looks bad (imo). So which size to pick? The only solution I can think of is to let the theme decide or to provide a settings option. Maybe you can take a look at how Workspace Grid did this. Feel free to send a pull request with a solution.

**Comment by toobaz** [comment]
> Maybe you can take a look at how Workspace Grid did this.

It seems like it used the ``ws-switcher-label`` class:

https://github.com/zakkak/workspace-grid/blob/3.30/src/gridWorkspaceSwitcherPopup.js#L268

... that defines the size as ``2em``:

https://github.com/zakkak/workspace-grid/blob/3.30/src/stylesheet.css#L74

I see your worry that some long names might be truncated... but it never happened to me, and if it happened, that would be a minor concern... and in principle, it could happen even now.

I can try a PR if you like the solution... although it would be my first javascript PR ever, not really sure of the result.

**Comment by mzur** [comment]
Feel free to send a PR if you like. Ideally I'd like the following solution:

- A custom CSS stylesheet for this extension that makes sure the workspace labels are centered in their respective indicator box.

- A new settings option that allows the configuration of a custom label size with a sensible default.

**Comment by ebeem** [comment]
implemented and tested in #152, please let's discuss any issue with the current implementation (if any) in the PR.
