### ISSUE TITLE
Two finger horizontal swipe overrides horizontal scrolling, opens workspace switcher

### ISSUE THREAD

**Issue by Manningham** [mzur/gnome-shell-wsmatrix#144]
Whenever I need to horizontally scroll with a two finger swipe, I end up in the workspace switcher instead. 

Apologies if this isn't actually coming from gnome-shell-wsmatrix, but I only see the problem with this extension enabled. Unfortunately this makes the otherwise wonderful extension very difficult to use and I don't see a setting to alter this behavior.

Otherwise, I love this extension! Thanks very much for your work on it.

**Comment by mzur** [comment]
I don't have this issue on my machine (GNOME 3.36). Could you please share more details on your setup (distro, GNOME version, etc.). Does this also happen if you disable all other extensions that you might have installed?

**Comment by Manningham** [comment]
GNOME 3.36.8

**Comment by Manningham** [comment]
Ah apologies, it was definitely not a gnome-shell-wsmatrix issue. After ruling out the other extensions I use, I remembered that I had been using xbindkeys for some things in the past - the configuration file looked harmless but I removed xbindkeys anyways and the issue disappeared.

Sorry to bug you, and thanks again for this extension :)
