### ISSUE TITLE
Allow configuration of workspace switcher popup timeout

### ISSUE THREAD

**Issue by tom-james-watson** [mzur/gnome-shell-wsmatrix#15]
I find the workspace switcher popup stays visible too long to be comfortable. I switch workspaces _a lot_ and it ends up feeling like it's getting in the way. I actually started using https://extensions.gnome.org/extension/959/disable-workspace-switcher-popup because of this.

Could we add an option for configuring the timeout length?

From diving into the code a bit, it looks like it is controlled by [DISPLAY_TIMEOUT](https://github.com/GNOME/gnome-shell/blob/master/js/ui/workspaceSwitcherPopup.js#L10) and you would need to override the `display` method of `WorkspaceSwitcherPopupList` - https://github.com/GNOME/gnome-shell/blob/master/js/ui/workspaceSwitcherPopup.js#L146-L156.

Thanks! I'd be happy to hack on the extension but I've never worked on anything GNOME before and can't see any instructions for how to get a dev environment set up. If you add some info to the README I could have a hack on it if you like.

**Comment by mzur** [comment]
Funny, somebody else [thinks](https://github.com/mzur/gnome-shell-wsmatrix/issues/10#issuecomment-480817974) that it is gone too soon. But I like their idea that the popup should be visible as long as the keys are pressed. In your case it would be gone quicker and in their case it would stay there for longer. I don't know if this can be implemented, though. Maybe this change should be proposed upstream in GNOME itself, instead.

**Comment by tom-james-watson** [comment]
Heh, I guess it depends on how you use your grid. I always have my workspaces arranged in the same way so I don't need to think whilst changing spaces. 

And yeah, I think that's how it used to work on Gnome 2 back in the day. I think that would be a good solution, or if not a configurable timeout seems like a good compromise.

**Comment by mzur** [comment]
You can open an issue in the [GNOME Shell repo](https://gitlab.gnome.org/GNOME/gnome-shell) and ask the GNOME guys what they think of this. I'd support this change.

**Comment by mzur** [comment]
This has been implemented in #19 and will be available with the next release.

**Comment by tom-james-watson** [comment]
Amazing - thanks, guys!
