### ISSUE TITLE
[Feature Request] diagonal animation

### ISSUE THREAD

**Issue by jgabriel98** [mzur/gnome-shell-wsmatrix#151]
First or all, thank for this amazing extension. It makes my desktop much more fluid and productive.

## Feature request description
I don't know how much effort this would take, but i thinks it would be nice to add diagonal animation, since i believe it is a very common movement.

###### note: for a less verbose explaining, i will pretend that pressing arrow keys are the shortcuts to switch workspaces.

The animation would be triggered by two directional arrow keys are pressed (e.g. `↑`+`→`, or `→`+`↓`, etc).

#### Possible problems:
 - Probably the two keys will never be pressed at the same time, so how can we distinguish a vertical/horizontal from a diagonal movement?
 Those are the two solutions i could think of:
  1. We can add a delay between **when the keys are pressed** and **when the animation starts**, so then it will have enough time for both keys be pressed (in case of a diagonal movement). In other words, way for another keypress  for a amount of time. Like this:
  
  ![apagar2](https://user-images.githubusercontent.com/37881981/113089413-fcbca500-91bd-11eb-870a-b526b2455958.png)
  you can mannualy test key press delay [here](https://jsfiddle.net/philfreo/56qGM)

   2. We can change the way that the animation works: the animation change direction dynamically (while it's running).
     - e.g.: when the current workspace is switching to the right, if i press down it will change the animation to that direction on "middle run". Here's a picture showing  the animation movement:

![apagar](https://user-images.githubusercontent.com/37881981/113088455-fa594b80-91bb-11eb-9c5b-c98876853a2c.png)

For me the first solution feels workarround-ish, and the second more natural and pleasurable but also seems to be more tricky.

**Comment by jgabriel98** [comment]
I've never developed for gnome environment neither for a gnome extension.
And also i'm pretty shorthanded surrently, since i'm working on my Undergraduate thesis for my Computer Science graduation.

But after that (in 4 months)i think i can try to implement this. Or at least give my best to help

**Comment by mzur** [comment]
This would be very hard to implement (if possible at all), I'm afraid. In the recent PR for GNOME 3.38 support I had to disable animations altogether because fixing them was too cumbersome and introduced too much new code. If you want to contribute, please consider helping out in one of the [help wanted](https://github.com/mzur/gnome-shell-wsmatrix/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issues. Of course I can't stop you trying to implement the diagonal animation :wink: Until then I'll close this issue.

**Comment by ebeem** [comment]
actually, this is already implemented in #152 (the diagonal animation part)
However, this will only work if you are moving let's say in a 2x2 workspace setup from `workspace#1` to `workspace#4` immediately.
meaning, you don't go through `workspace#2` or `workspace#3`.

I think the delay idea is possible maybe, you will need to implement it in the function `_keyPressHandler` in `WorkspaceSwitcherPopupBase.js`
