### ISSUE TITLE
GNOME 40 Support?

### ISSUE THREAD

**Issue by darylf** [mzur/gnome-shell-wsmatrix#156]
I recently updated to Fedora 34, which ships with GNOME 40, and the extensions page tells me this extension is "outdated".

I'm not sure what's involved in updating and supporting the latest GNOME, but I love this extension and severely miss it.

I'm not sure if there's anything I can do to help: provide logs or screenshots or anything.

**Comment by mzur** [comment]
We are working on it in #152. You can test the changes and report bugs there if you like.
