### ISSUE TITLE
I have black areas only no thumblails on swither

### ISSUE THREAD

**Issue by bots-business** [mzur/gnome-shell-wsmatrix#159]
I have black areas only no thumblails on swither. 
Switcher is worked but I have not any preview on it. I need small pictures on that boxes.

Please help me to describe this bug. What info we need to fix?

**Comment by mzur** [comment]
Did you enable the "show thumbnails" option in the extension preferences?

**Comment by bots-business** [comment]
Yes. Also I have 2 monitors. Maybe it is matter.

![image](https://user-images.githubusercontent.com/38240269/122019180-e0b4c100-ce06-11eb-92bb-9d6cf47d928b.png)

**Comment by mzur** [comment]
Are there errors related to this extension in `journalctl /usr/bin/gnome-shell`?

**Comment by bots-business** [comment]
![image](https://user-images.githubusercontent.com/38240269/122143268-7cd8d980-ce94-11eb-881e-211a1b769ac4.png)

**Comment by bots-business** [comment]
Getting invalid resource scale property
Failed to set CRTC gamma: drmModeCrtcSetGamma on CRTC 46 failed: Access denied

**Comment by mzur** [comment]
Do you find anything that mentions `wsmatrix@martin.zurowietz.de` in the log? What OS and GNOME version do you use?

**Comment by bots-business** [comment]
Yes, I have this error:

JS ERROR: Error: Too few arguments to method Clutter.Actor.set_allocation: expected 2, got 1
                                              vfunc_allocate@/home/user/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/ThumbnailWsmatrixPopup.js:65:12

**Comment by mzur** [comment]
Your version of this extension is probably too new. The line was modified for GNOME 3.38 support in v5 of this extension. You should use v4 of this extension.

**Comment by bots-business** [comment]
Thank you! It is fixed
