### ISSUE TITLE
Make use of workspace thumbnails optional

### ISSUE THREAD

**Issue by tom-james-watson** [mzur/gnome-shell-wsmatrix#16]
I'd prefer to have the default solid colours for the workspace switcher popup instead of thumbnails of the workspaces themselves. 

Basically I just want this but in a grid:

![image](https://user-images.githubusercontent.com/3852719/56455721-5bd2d780-6362-11e9-90da-97c87a00ddad.png)

(I don't care about the directional arrows).

Thanks! Likewise with my other issue - I could have a look into this myself if you provide some pointers with how to setup a dev environment for the extension.

**Comment by mzur** [comment]
I need to think about this. The whole point of this extension originally was to provide a 2D layout of workspaces *with* thumbnails in the popup. But if this extension really should replace Workspace Grid, the scope might become larger.

I don't like the idea of having only the arrows for up and down although you can switch left and right, too. I think these arrows are provided by the theme and can't be influenced by an extension. In that case, I'd rather not show the arrows at all and only highlight the current workspace.

Feel free to have a go at this. But I can't promise that I will add it to Workspace Matrix right now. I'll wait for the results of the [poll](https://github.com/workspace-grid/workspace-grid/issues/120#issuecomment-485001084) I'm about to open in the next few days and see if enough users would be interested in this feature.

The dev environment is simple. The extension is installed in `~/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de`. You can clone this repo somewhere and replace the extension directory with a link to `wsmatrix@martin.zurowietz.de` of this repo. Whenever you restart GNOME (Alt+F2 and the `r` command), your newest changes to the files will be applied. You can use `log();` for debugging in the code. The log output can be shown continuously with `journalctl -f /usr/bin/gnome-shell`. Whenever you change something in the preferences UI, run `make` once in the repo.
