### ISSUE TITLE
Workspace Matrix is not fully working on Gnome 40.3.0

### ISSUE THREAD

**Issue by louay-hesham** [mzur/gnome-shell-wsmatrix#166]
After upgrading to Gnome 40.3.0 I noticed the following issues with Workspace Matrix:
1. When navigating through workspaces, their previews are empty (just blank boxes)
2. When navigating through workspaces, the animation is totally messed up. Going to the right and left is fine, but the animations when navigating to a bottom or top ws makes the animations of going to right and left ws respectively. It does end up where I want but the animation is incorrect
3. I can't open the extension settings window. Instead I get this error:

The settings of extension wsmatrix@martin.zurowietz.de had an error:
```
Gtk.BuilderError: /home/louay/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/settings.ui:9:35 Invalid property: GtkBox.margin_left
```

Stack trace:
```
_init@/home/louay/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/prefs.js:16:23
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
buildPrefsWidget@/home/louay/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/prefs.js:145:17
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by mzur** [comment]
GNOME 40 is not fully supported yet. Please have a look at #152. Feel free to test the code of the PR and provide feedback.
