### ISSUE TITLE
workspaces overview not correct

### ISSUE THREAD

**Issue by rafaytaher** [mzur/gnome-shell-wsmatrix#167]
![image](https://user-images.githubusercontent.com/4658993/130593006-b5741d54-fd8f-4d3c-84c7-9c1e4b68e36f.png)

i have 3 workspaces and the workspaces overview is just wrong.

**Comment by mzur** [comment]
Which GNOME version do you use?

**Comment by rafaytaher** [comment]
![image](https://user-images.githubusercontent.com/4658993/130755757-dd63a677-c50c-477c-80bb-d998b7ff7fff.png)

please see in the screenshot

**Comment by mzur** [comment]
Please make sure that you use version 23 of this extension (from extensions.gnome.org) or v4.0.3 (from GitHub).

**Comment by rafaytaher** [comment]
ok I installed 27 version. let me try as you said. Thanks for quick response.

**Comment by rafaytaher** [comment]
> Please make sure that you use version 23 of this extension (from extensions.gnome.org) or v4.0.3 (from GitHub).

this has worked! 

![image](https://user-images.githubusercontent.com/4658993/130758314-30587670-22f9-426a-ae84-40f354469406.png)
