### ISSUE TITLE
Support for gnome 40

### ISSUE THREAD

**Issue by shoshtari** [mzur/gnome-shell-wsmatrix#169]
Is there any chance we have this extension with gnome 40?

**Comment by shoshtari** [comment]
Oh! i apologize! 
i didn't take a look at PRs! i am sorry for this issue.

**Comment by ElijahLynn** [comment]
Crosslinking issue for 40 > https://github.com/mzur/gnome-shell-wsmatrix/pull/152

**Comment by mzur** [comment]
The new version of this extension supporting GNOME 40 and 41 should also be available on extensions.gnome.org now.
