### ISSUE TITLE
Popup timeout bug

### ISSUE THREAD

**Issue by pnkov** [mzur/gnome-shell-wsmatrix#172]
Found issue in `gnome-40` branch with popup timeout.
`Time to show the popup (ms)` setting has no effect after deletion of `_resetNoModsTimeout` [here](https://github.com/mzur/gnome-shell-wsmatrix/commit/0dcd2e75a9e91612ba5612457b7d8e64b657b8f5#diff-e6ad3a4bc914923c6ffe7b836b808e15e4e8e440c5dfcc07df7697d231421740L112).
Issue fixed for me when I added this method back.

**Comment by mzur** [comment]
Thanks! I was wondering what the function was about and forgot that I deleted it.
