### ISSUE TITLE
gnome-shell crashes

### ISSUE THREAD

**Issue by deefactorial** [mzur/gnome-shell-wsmatrix#18]
I am experiencing a freezing when switching workspaces where gnome-shell crashes and restarts gnome here is the relevant stack trace I could find in `journalctl` 

this has happened to me 4 times in the last two days.
Gnome-version: 3.28.2

```
Apr 24 09:57:40 big-oryx-02 gnome-shell[11980]: Object Meta.WindowActor (0x5623092db000), has been already deallocated - impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
Apr 24 09:57:40 big-oryx-02 org.gnome.Shell.desktop[11980]: == Stack trace for context 0x5623038914c0 ==
Apr 24 09:57:40 big-oryx-02 org.gnome.Shell.desktop[11980]: #0 0x562303d1fa00 i   resource:///org/gnome/shell/ui/windowManager.js:1787 (0x7f2022a24670 @ 113)
Apr 24 09:57:40 big-oryx-02 org.gnome.Shell.desktop[11980]: #1 0x7ffd2bdc8cf0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f2022db5de0 @ 71)
Apr 24 09:57:40 big-oryx-02 org.gnome.Shell.desktop[11980]: #2 0x7ffd2bdc8db0 b   self-hosted:916 (0x7f2022df12b8 @ 367)
Apr 24 09:57:40 big-oryx-02 org.gnome.Shell.desktop[11980]: #3 0x562303d1f970 i   resource:///org/gnome/shell/ui/windowManager.js:1957 (0x7f2022a24c48 @ 97)
Apr 24 09:57:40 big-oryx-02 org.gnome.Shell.desktop[11980]: #4 0x7ffd2bdcac70 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f2022db5de0 @ 71)
Apr 24 09:57:40 big-oryx-02 org.gnome.Shell.desktop[11980]: #5 0x562303d1f8a0 i   /home/dominique/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/WmOverride.js:202 (0x7f1ff16eb6f8 @ 1155)
Apr 24 09:57:40 big-oryx-02 org.gnome.Shell.desktop[11980]: #6 0x7ffd2bdcb970 b   self-hosted:922 (0x7f2022df12b8 @ 469)
```

**Comment by mzur** [comment]
Which other extensions do you use? Does this error also happen when you disable this extension?

**Comment by deefactorial** [comment]
the only other extension I have is `Gtile` no it doesn't happen when I disable this extension. I find that it happens most frequently when I'm screen sharing with zoom call, and switching workspace, but that's not the only case, it's also happened other times when I haven't been on a zoom call.

**Comment by mzur** [comment]
Do you have any reliable way to reproduce this? I'm using GNOME 3.28.3 and don't experience any issues. Maybe this can be solved with an update?

The line that is referred to in your stack trace seems to be [this one](https://github.com/mzur/gnome-shell-wsmatrix/blob/48b1f9136e5e9b2cf590ea95b0449fb3aee09bff/wsmatrix%40martin.zurowietz.de/WmOverride.js#L202). That part of Workspace Matrix does not differ from the default code.

**Comment by tadiou** [comment]
@deefactorial I too have this issue (and debugging it has been hell), but I don't think it's specific to this plugin. I was able to replicate it with and without (and the old Workspace Grid too), but there hasn't been a really common thread. I upgraded from 3.28.2 (ubuntu 18.04), to 3.30 (ubuntu 18.10) in hopes that that would solve it here.

**Comment by deefactorial** [comment]
I have been able to live with it so far by not switching workspaces during a zoom call, or if I do have to switch workspaces, I wait until the zoom call stabilizes before switching, and that seems to work. ubuntu 18.04 is still on 3.28.2 hopefully they will update to 3.28.3 soon, or perhaps I can find a ppa with 3.28.3 on it. I will try to update to 3.28.3 soon.

**Comment by mzur** [comment]
Please reopen if this is still relevant.
