### ISSUE TITLE
Testing extension without a display

### ISSUE THREAD

**Issue by aminvakil** [mzur/gnome-shell-wsmatrix#186]
I maintain this extension in https://github.com/aminvakil/aur and wanted to try testing basic stuff before deploying it to https://aur.archlinux.org/packages/gnome-shell-extension-workspace-matrix/, so I tried executing
```
gnome-extensions enable wsmatrix@martin.zurowietz.de
```
after the package has been built and obviously I got this error:
```
(gnome-extensions enable:3205): dconf-WARNING **: 05:59:38.418: failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY
```
More info: https://github.com/aminvakil/aur/runs/3728812829?check_suite_focus=true#step:12:10

What do you suggest for fixing this? Or do you have any ideas testing it another efficient way?

**Comment by mzur** [comment]
Sorry, no idea. I had a quick look at how [GNOME Shell](https://gitlab.gnome.org/GNOME/gnome-shell) is tested but this didn't help. Also I experimented with `xvfb` in a Ubuntu Docker container (`apt install --no-install-recommends xvfb gnome-shell dbus-x11` and then `xvfb-run gnome-shell --x11`) but this disn't work either. `gnome-extensions enable` works then but you don't get any error message if there is an error in the extension. Maybe you can find out more.

**Comment by aminvakil** [comment]
No problem at all! Thanks for taking a look at this!
I couldn't make it work either, if that's fine let's keep this issue open, and see if someone else had any other idea.

**Comment by mzur** [comment]
I'll close this since no one showed up in two years. Please let me know if you want this reopened.

**Comment by aminvakil** [comment]
It's ok, I'll let you know if I found something later, thanks again!
