### ISSUE TITLE
$$$ to @ebeem and @mzur for Gnome 40 support!

### ISSUE THREAD

**Issue by ElijahLynn** [mzur/gnome-shell-wsmatrix#187]
From: https://github.com/mzur/gnome-shell-wsmatrix/pull/152
> @ElijahLynn If your [offer](https://github.com/mzur/gnome-shell-wsmatrix/pull/152#issuecomment-867987244) still stands, all the credit goes to @ebeem :wink: 

Issue was closed so I couldn't reply. Heck yeah it still stands, AND I just updated the extension and it works perfectly just like it used to!

Would love to send some $$$ your way @ebeem! If you would like that, please lemme know how to do that, I see you are in Saudi Arabia, so not sure if you can use PayPal, or Venmo or Cash app etc. Would love to send you some cash! And you too @mzur!

_Originally posted by @mzur in https://github.com/mzur/gnome-shell-wsmatrix/pull/152#pullrequestreview-763428404_

**Comment by mzur** [comment]
Our PayPal links are in the sponsoring information of this repo. There should be a button below the comment box of this issue, too.

**Comment by ebeem** [comment]
Thanks @ElijahLynn, I really appreciate your support.
As @mzur mentioned, both of our PayPal information can be found in the repo.

Thanks again!

**Comment by ElijahLynn** [comment]
Wonderful!

I set a total of $130 USD to both of you, but it did take transaction fees, so :shrug:. 

Thanks again for your work on this, you made my life much better on an hourly basis!!!

![image](https://user-images.githubusercontent.com/1504756/136634256-8246a808-3c84-4bbf-bb9b-f26d52b154c6.png)
![image](https://user-images.githubusercontent.com/1504756/136634257-7b994c65-ee3b-469f-8f47-104e7f70b597.png)

**Comment by mzur** [comment]
I received both 82.88 EUR and 24.86 USD. Did something go wrong? :confused:

**Comment by mzur** [comment]
> Oh interesting, appears that way. Is your email linked to both?

Not that I know of :smile: I'll forward the money to @ebeem.

**Comment by ebeem** [comment]
Many thanks @ElijahLynn & @mzur 
I really appreciate your support.
