### ISSUE TITLE
Previews are not updated when using with dynamic wallpaper

### ISSUE THREAD

**Issue by AlpSha** [mzur/gnome-shell-wsmatrix#192]
I'm using dynamic wallpapers that change by the time of the day. But the workspace preview keeps showing the wallpaper that is active when I first login. For example, currently there is sunlight but the previews still show the night wallpaper. It would be great if you could solve this.

Many thanks.

**Comment by mzur** [comment]
Is dynamic wallpapers a separate extension?

**Comment by AlpSha** [comment]
It is set by the tweaks tool. Using xml files. 
![image](https://user-images.githubusercontent.com/41454613/140776765-2646baba-99f4-42ba-85bd-3780a08b6eda.png)

Here is an example xml file for dynamic wallpapers.

`<background>
	<starttime>
		<year>2021</year>
		<month>11</month>
		<day>01</day>
		<hour>00</hour>
		<minute>00</minute>
		<second>00</second>
	</starttime>
	
	<static>
		<file>/home/{{username}}/Pictures/Monterey/16.jpg</file>
		<duration>14400.0</duration>
	</static>

	<static>
		<file>/home/{{username}}/Pictures/Monterey/1.jpg</file>
		<duration>3600.0</duration>
	</static>

	<static>
		<file>/home/{{username}}/Pictures/Monterey/2.jpg</file>
		<duration>3600.0</duration>
	</static>

	<static>
		<file>/home/{{username}}/Pictures/Monterey/3.jpg</file>
		<duration>3600.0</duration>
	</static>

	<static>
		<file>/home/{{username}}/Pictures/Monterey/4.jpg</file>
		<duration>3600.0</duration>
	</static>

	<static>
		<file>/home/{{username}}/Pictures/Monterey/5.jpg</file>
		<duration>3600.0</duration>
	</static>

	<static>
		<file>/home/{{username}}/Pictures/Monterey/6.jpg</file>
		<duration>3600.0</duration>
	</static>

	<static>
		<file>/home/{{username}}/Pictures/Monterey/7.jpg</file>
		<duration>3600.0</duration>
	</static>
	
	<static>
		<file>/home/{{username}}/Pictures/Monterey/8.jpg</file>
		<duration>3600.0</duration>
	</static>	

  
	<static>
		<file>/home/{{username}}/Pictures/Monterey/9.jpg</file>
		<duration>3600.0</duration>
	</static>	


	<static>
		<file>/home/{{username}}/Pictures/Monterey/10.jpg</file>
		<duration>3600.0</duration>
	</static>	


	<static>
		<file>/home/{{username}}/Pictures/Monterey/11.jpg</file>
		<duration>3600.0</duration>
	</static>	


	<static>
		<file>/home/{{username}}/Pictures/Monterey/12.jpg</file>
		<duration>3600.0</duration>
	</static>	


	<static>
		<file>/home/{{username}}/Pictures/Monterey/13.jpg</file>
		<duration>3600.0</duration>
	</static>	


	<static>
		<file>/home/{{username}}/Pictures/Monterey/14.jpg</file>
		<duration>3600.0</duration>
	</static>	


	<static>
		<file>/home/{{username}}/Pictures/Monterey/15.jpg</file>
		<duration>3600.0</duration>
	</static>	

	<static>
		<file>/home/{{username}}/Pictures/Monterey/16.jpg</file>
		<duration>18000.0</duration>
	</static>
</background>
`

**Comment by mzur** [comment]
This is the first time I've heard of this feature but it seems to be GNOME built-in. Maybe there is an event to which this extension can subscribe to update the thumbnails whenever the wallpaper changes. Everyone feel free to start working on this.

**Comment by ebeem** [comment]
I never thought about the dynamic wallpaper feature, maybe the caching part is actually affecting this.

**Comment by ebeem** [comment]
@AlpSha  a little bit complicated to test the dynamic wallpaper for me, I tried to change the wallpaper though and the extension rendered the new one in the switcher correctly. I am afraid that this an upstream issue, can you disable the extension and let us know whether you can see the dynamic wallpaper changing in the overview or not?

**Comment by AlpSha** [comment]
@ebeem Dynamic Wallpapers not updating on Zorin OS's default overview either. I disabled this extension and tried it. It is the same result. It seems that this is nothing to do with you. Sorry guys.

By the way, I found that issue on web. It seems it's fixed on newer versions of Gnome.
https://gitlab.gnome.org/GNOME/mutter/-/issues/1597

**Comment by ebeem** [comment]
I hope it gets fixed soon, thanks for updating us about this issue.
