### ISSUE TITLE
Feature request: select workspace from matrix with a mouse

### ISSUE THREAD

**Issue by rsb00od** [mzur/gnome-shell-wsmatrix#204]
Can mouse click for selecting certain workspace be implemented in some new version?

**Comment by ebeem** [comment]
Sure, that will definitely come with #60,
currently, only hovering workspaces is supported, make sure you enable the option `Select workspaces with mouse hover on popup` in your extension preferences.

**Comment by rsb00od** [comment]
Great, but I see only these options in version 27, shell version 3.38
![wsm27](https://user-images.githubusercontent.com/97163904/151544860-ee406312-f504-4890-a2f2-7ef960b78307.png)
.

**Comment by rsb00od** [comment]
Am i missing something? Some other extension has to be installed so I can see `Select workspaces with mouse hover on popup` ?

OS is Debian stable.

**Comment by ebeem** [comment]
you're running an old version.
You should be able to see this feature once you upgrade to `gnome 40`
