### ISSUE TITLE
Popup does not vanish with mod-key-release anymore

### ISSUE THREAD

**Issue by Grinzold** [mzur/gnome-shell-wsmatrix#207]
Hi there,

with 'popup-timeout=0' the popup does not vanish anymore.  It just stays indefinitely.

Expected behaviour: it should vanish with the release of the modifier keys.

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish

$ gnome-shell --version
GNOME Shell 40.5

$ grep -r '"version":' .
./metadata.json:  "version": 33

Not sure if this translates to version v6.4

**Comment by ebeem** [comment]
It's related to `v6.4`, issue #200 has the same problem (but with a special case).
In your case shouldn't something is fishy. If the popup doesn't disappear without performing an special action, then you must have a modifier key used by default which doesn't make sense. Can you please let us know if you have any special use case that causes this behavior or a package/configuration you are using that you think it causes it?

**Comment by ebeem** [comment]
Can you please check with an earlier release of wsmatrix? like `v6.3` or ` v6.2`.
Let me know if you face the same problem or that fixes it.

**Comment by ebeem** [comment]
Also let me know please if you happen to run this Ubuntu machine in a virtual machine.

**Comment by Grinzold** [comment]
No virtual machine

It was working perfectly until a few days ago.  I am not sure what was updated when.  Maybe gnome was also updated...
Is there an 'installation history' for gnome-extensions somewhere?  (I use the gnome extension website to manage the extensions.)

I use the modifiers: <ctrl> + <alt>  

This is in my prefs:

switch-to-workspace-down=['<Primary><Alt>Down']
switch-to-workspace-left=['<Primary><Alt>Left']
switch-to-workspace-right=['<Primary><Alt>Right']
switch-to-workspace-up=['<Primary><Alt>Up']

In the metadata.json there is written version 33.  How do you translate this to v6.4 or v6.3...?

Thanks for your help.

**Comment by Grinzold** [comment]
The problem above, I have with my desktop.  I also use a laptop w/ identical versions.  No problem there.

Is there any log/debug output to be enabled?

**Comment by ebeem** [comment]
Trying out https://github.com/mzur/gnome-shell-wsmatrix/releases/tag/v6.3 and lettings us know whether it fixes it or not will probably help.

**Comment by Grinzold** [comment]
Sorry for my ignorance, but how do I do that?

Just unpack everything under .local/share/gnome-shell/extensions?

Any log/debug output to check what is going on?

How do I do a fresh start?  E.g. get rid of the 'dconf' entries?

**Comment by ebeem** [comment]
you don't need to do anything with `dconf` yet, just remove the old extension folder in `~/.local/share/gnome-shell/extensions`, the folder's name should be something like `wsmatrix@martin.zurowietz.de`.
Then replace it with the one you download and extract from the `release` page

**Comment by Grinzold** [comment]
All have the same behaviour. I went down to version v6.0.  With timeout=0 the popup is stuck until I click with the mouse or I hit esc...

Version is always shown as '-1', though.  Can't you put there the actual version?

**Comment by ebeem** [comment]
Thanks for your feedback, it seems like you're not the only one facing a similar issue. #200 also mentions the issue and it's probably a `GNOME` issue.
I will investigate further and keep you updated.
Thanks for your feedback.

**Comment by mzur** [comment]
Maybe related to https://github.com/mzur/gnome-shell-wsmatrix/issues/219?

**Comment by mzur** [comment]
This sounds very much like #219. Since the assumed cause is a missing event returned by Clutter, maybe a Clutter update broke this behavior. This can continue in #219.
