### ISSUE TITLE
The extension suddenly stopped working on Ubuntu 20.04

### ISSUE THREAD

**Issue by Michael-E-Rose** [mzur/gnome-shell-wsmatrix#213]
The extension suddenly stopped working this morning; all I have is a column of 4 workspaces. I cannot activate the extension via Extension (on the desktop), I can activate the extension both in Chrome and Firefox, but without effect and on the next restart it's all gone again.

I asked the question on SO: https://askubuntu.com/q/1397303/334172 Not sure it's my settings (which I didn't change since yesterday), the package (looks unlikely) or Gnome.

**Comment by ebeem** [comment]
I am not sure if this is an issue with this extension `wsmatrix` or with the `chrome-extension` that allows you to install gnome extensions from the web.

`GNOME 40` has an application named `Extensions`, this application shows you the install extensions and allows to configure them. Can you check if this `Extensions` applications shows the `Workspace Matrix` in the list or not?

If it's not there, then maybe you want to just install it manually with the method mentioned here https://github.com/mzur/gnome-shell-wsmatrix#manual-linux-method

**Comment by mzur** [comment]
I use Ubuntu 20.04, too, and the extension works without issues. Please also look for error messages in the log output when you execute `journalctl /usr/bin/gnome-shell`.

**Comment by Michael-E-Rose** [comment]
I only have one other extension, Desktop Icons, and that works fine.
As soon as I install Workspache Matrix, the slider moves to off immediately.

Here is the first output related to the WS matrix:
```
Mär 12 14:40:20 panther3 gnome-shell[12492]: JS WARNING: [/home/panther/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com/extension.js 1268]: reference to undefined property "_controls"
Mär 12 14:40:20 panther3 gnome-shell[12492]: JS ERROR: Extension workspace-grid@mathematical.coffee.gmail.com: TypeError: Main.overview._controls is undefined
overrideWorkspaceDisplay@/home/panther/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com/extension.js:1268:25
enable@/home/panther/.local/share/gnome-shell/extensions/workspace-grid@mathematical.coffee.gmail.com/extension.js:1533:5
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:351:26
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:601:18
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:576:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:610:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:641:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
start@resource:///org/gnome/shell/ui/main.js:146:5
@<main>:1:47
Mär 12 14:40:21 panther3 gnome-shell[12492]: GNOME Shell crashed with signal 11
```

**Comment by Michael-E-Rose** [comment]
I reinstalled GNOME Tweaks, and now finally I can slide Extensions on again. Weird stuff, and thanks for the help!

**Comment by mzur** [comment]
Your log output indicates that you use the Workspace Grid extension. This is not the same as Workspace Matrix.

**Comment by Michael-E-Rose** [comment]
So much I know, but a) Workspace Grid was never installed and b) isn't Workspace Matrix based on Worspace Grid?

**Comment by mzur** [comment]
> a) Workspace Grid was never installed

It's definitely in your log output: `workspace-grid@mathematical.coffee.gmail.com`

> b) isn't Workspace Matrix based on Worspace Grid

Only feature-wise. Workspace Matrix was written from scratch.
