### ISSUE TITLE
workspace thumbnails are disabled on their own 

### ISSUE THREAD

**Issue by icegood** [mzur/gnome-shell-wsmatrix#214]
Have no idea why and when they are disabled. Maybe, you will help me to find appropriate logs...
To reenable i should always go to extension settings and disable and re-enable again "Show workspace thunbnails in popup"

System: Ubuntu 21.10

**Comment by ebeem** [comment]
So the grid shows up but the the thumbnails are blank?
or the grid doesn't show up at all?

**Comment by mzur** [comment]
Please reopen if you can provide more information.
