### ISSUE TITLE
Fix hiding of popup with timeout=0

### ISSUE THREAD

**Issue by mzur** [mzur/gnome-shell-wsmatrix#219]
Previously the popup stayed on the screen as long as you kept <kbd>CTRL</kbd>+<kbd>ALT</kbd> pressed. Now, you either have to confirm the workspace selection with enter or set up a timeout for it to disappear. (reported here: https://github.com/mzur/gnome-shell-wsmatrix/pull/217#issuecomment-1106255080)

Apparently this is because of a missing event (see: https://github.com/mzur/gnome-shell-wsmatrix/pull/217#issuecomment-1106623552).

**Comment by ElijahLynn** [comment]
Thank you for putting this up here, just came here to open an issue for this!

**Comment by ebeem** [comment]
fixed for me after upgrading to `GNOME Shell 42.1`
It will be great if someone can upgrade and confirm

**Comment by ElijahLynn** [comment]
> fixed for me after upgrading to `GNOME Shell 42.1`
> It will be great if someone can upgrade and confirm

Confirmed. I updated from Gnome 42.0 to 42.1 and did an <kbd>alt + F2</kbd> then typed <kbd>r</kbd> then <kbd>enter</kbd> and the popup is now working the way it used to on Gnome 41, appearing to respect my previous timeout I had set!

**Comment by mzur** [comment]
This is resolved then. Thanks for testing!

**Comment by ElijahLynn** [comment]
I just switched to Wayland from X11 and the pop up doesn't close automatically anymore.

**Comment by humanplayer2** [comment]
I'm on GNOME 42.1 on two machines, both with Workspace Matrix v. 34. Both I recently updated from GNOME 41 and a previous extension version. 
On my Wayland laptop, never had the issue. 
On my X11 desktop, I had the issue, found this, changed the time-out to 500ms, and when I now tried to duplicate the problem, it doesn't appear (with time-out 0 ms).

If it matters, then on both machines, I use  ```Meta``` for all workspace changes, and am on Pop!_OS 22.04. If I can supply other info, then please tag me.

**Comment by mzur** [comment]
So does anyone still experience this issue?

**Comment by humanplayer2** [comment]
Super erratically. I experience it once in a when changing workspaces *and* dragging files with me (i.e., keeping LMB down). It just happened while writing this. To check if I was on Wayland or X, I tried to restart X (Alt + F2, r), which told me I'm in X, now. After restarting, I cannot get the popup to stick again. I'll gladly open a new issue if I find a way to consistently duplicate the behavior.

**Comment by mzur** [comment]
Ok, thanks!
