### ISSUE TITLE
Workspacematrix has to be disabled and enabled after each reboot/ gnome-shell restart

### ISSUE THREAD

**Issue by Creative-user-name** [mzur/gnome-shell-wsmatrix#228]
## Description of Issue

After each reboot of the system, workspacematrix doesn't work but is displayed as active in the gnome-extensions-app. Disabling (not uninstalling!) and re-enabling fixes it and it works until the next reboot.

I reinstalled it several times and tried to find a solution in the web. Maybe only I have it.

## System-specs:

Pop_OS! 22.04 with gnome 42.1

extension was installed via extensions.gnome.org

## Thank you

Thank you in advance for reading. I really like this program and fixing this would make it perfect. 

_**I am of course compliant to giving logs or anything else if needed**_

**Comment by mzur** [comment]
Please look in the logs (`journalctl /usr/bin/gnome-shell`) if there is anything connected to this extension. Is it the same issue if your reload GNOME Shell instead of rebooting (<kbd>Alt</kbd>+<kbd>F2</kbd> and the `r` command on Xorg, log out and log in on Wayland)?

**Comment by Creative-user-name** [comment]
Thank you for the reply!
I am working answering your questions. But first: Yes, after restarting the gnome shell via alt + f2 and r, wm-matrix stops working as well.

**Comment by Creative-user-name** [comment]
I don't know how to open the logs (I'm not power-user enough to know how). I found them, but nano doesn't do the trick

**Comment by mzur** [comment]
You just have to execute the command `journalctl /usr/bin/gnome-shell` in the console. It will print the logs in the `less` pager. There, you can type `/wsmatrix` and then hit <kbd>Enter</kbd> to search for log entries related to this extension. Hit <kbd>q</kbd> to close `less`.

**Comment by Creative-user-name** [comment]
Excuse my lack of knowledge, now I have it in front of me. I don't really understand what it means though. from what I can see this isn't the case. Might I bother you with a screenshot of the output?

**Comment by Creative-user-name** [comment]
![image](https://user-images.githubusercontent.com/87444578/169977582-599f850b-092a-45dc-a867-703eca4989cc.png)

**Comment by mzur** [comment]
That's exactly what we're looking for. Is this all of the error message?

**Comment by Creative-user-name** [comment]
I think I found a solution: If you disable the "Cosmic Workspaces" extension it does work after reboot and gnome-shell-restart. If anybody else has this problem, they are welcome to confirm. This issue is now obsolete. 
Thanks @mzur for this wonderful extension and the immediate help on this issue!
I will close the issue in one week
