### ISSUE TITLE
Can't drag/drop from second display in panel-matrix

### ISSUE THREAD

**Issue by cponder** [mzur/gnome-shell-wsmatrix#231]
I have the workspace-matrix showing on my bottom-panel, but can only drag/drop application windows between my primary displays.
The workspaces are set up so the laptop & external displays are bound together, i.e. both displays change together when I switch workspaces.

I'm using Ubuntu 22.04.
I had been using 18.04 before, and the workspace-matrix on the bottom panel showed the application windows from both displays.
I don't see the windows from the second display in the current setup.

**Comment by mzur** [comment]
Have you enabled the switch "Show popup for all monitors" in the extension settings?

**Comment by cponder** [comment]
Going through all the `dconf Editor` menus, I don't see this option. Which category should it be under?
![dconf Extensions_Menu](https://user-images.githubusercontent.com/1598765/194529398-e72a45ac-4dfa-4189-b0a6-2fe052578d3c.png)

**Comment by mzur** [comment]
I'm talking about the settings window of this extension. You can access it via the official extensions website or through `gnome-shell-extension-prefs`.

**Comment by cponder** [comment]
What is the URL of the extensions website?

**Comment by cponder** [comment]
Also, the display I'm talking about is the one embedded into the bottom panel of my screen.
Maybe that's not controlled by your extension.

**Comment by cponder** [comment]
Is dash-to-panel who I need to talk to here?

**Comment by cponder** [comment]
I have "Show popup for all monitors" enabled, according to `gnome-shell-extension-prefs` and `gnome-extensions-app`.
One thing I have to say, though -- a lot of these extensions have a "multi-monitor" option; do I need to set this somewhere?
I only want the panel on my primary.

**Comment by cponder** [comment]
One thing I neglected to mention -- the cells in the Workspace Indicator only show what's on the primary monitor, not the external monitor:
![Panel Expanded](https://user-images.githubusercontent.com/1598765/196079865-de056915-bff2-4f9e-92a8-01b478b10ac4.png)
That's why I can;t drag.drop, since the thumbnails from the external monitor don't show up.
But this is really an issue of the Workspace Indicator, so I'll move the discussion there.

**Comment by cponder** [comment]
There's this issue filed:

https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/issues/341

**Comment by mzur** [comment]
Closing this, as it's an issue of another extension.
