### ISSUE TITLE
Matrix on bottom-panel will only show 6 workspaces

### ISSUE THREAD

**Issue by cponder** [mzur/gnome-shell-wsmatrix#232]
I set up my bottom-panel to show the workspace-matrix and am able to switch workspaces by clicking on the corrsponding cell.
Also I can drag/drop application-windows between cells.

The problem is that if I increase the number of workspaces greater than 6, the matrix disappears and is replaced by a counter of the number of workspaces.
If I click on the counter, it gives me a pop-up list of the workspaces, but I don't want that.

I'm using Ubunto 22.04.
I was using Ubuntu 18.04 before, and could show 12 or more workspace cells on the matrix.

**Comment by mzur** [comment]
I'm not familiar with this behavior. Could you please show a screenshot of this?

**Comment by cponder** [comment]
This is the `dconf` menu
![dconf](https://user-images.githubusercontent.com/1598765/194525003-b069c7d8-e1b1-4bd5-aca9-eb5c613d318f.png)
Here's the panel with 6 workspaces
![Panel Expanded](https://user-images.githubusercontent.com/1598765/194525103-4f4a9ac6-5f0d-40d3-b007-15ad4b285a95.png)
Here's the panel with 7 workspaces
![Panel Stupid](https://user-images.githubusercontent.com/1598765/194525173-21aff2dd-a3df-4021-a52e-6ce9069a5ed4.png)
There's plenty of room on my panel for a longer matrix. Also with just a number showing, I can't drag windows from one workspace to another.
The limit of 6visible workspaces  seems absolutely arbitrary to me. Can't you please raise it to 12?

**Comment by mzur** [comment]
What you show on the screenshots is nothing that is done by this extension. Do you have another extension installed that does this?

**Comment by cponder** [comment]
Is `dash-to-panel` who I need to talk to here?

**Comment by cponder** [comment]
I re-filed the issue here:
https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/issues/417

**Comment by cponder** [comment]
Her's the fix:
```
sudo vi /usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com/extension.js        # Set MAX_THUMBNAILS=20. Was =6.
gnome-extensions disable workspace-indicator@gnome-shell-extensions.gcampax.github.com
gnome-extensions enable  workspace-indicator@gnome-shell-extensions.gcampax.github.com
```
