### ISSUE TITLE
Gnome 42.2 Issues?

### ISSUE THREAD

**Issue by lautarodragan** [mzur/gnome-shell-wsmatrix#233]
I've just upgraded my Pop!_OS (did a clean format and install actually) and re-installed Workspace Matrix.

It now seems to get disabled whenever I restart the machine. It always comes back to vertical workspaces when I log into my account, even though it shows as ON in the Gnome Extensions store.

Turning it OFF and ON again "fixes" it, but I need to do it every time I log into my account.

It was working perfectly fine before upgrading the OS. I think I was using 21.04. I'm now using 22.04 LTS.

(As far as I know, for all intent and purposes, Pop!_OS can be considered an Ubuntu...)

BTW thank you so much for this beautiful extension. It makes my life as a dev so much better.

**Comment by mzur** [comment]
I'm using Ubuntu 22.04 and it works fine there. Do you still see this behavior with GNOME Shell 42.4?

**Comment by lautarodragan** [comment]
Thanks for replying! I'm still running 42.2 and still facing this. I don't want to manually update gnome because PopOS introduces some default customizations on top of it... I'll wait till Ubuntu/PopOS 22.10 comes out, which should be in a few weeks, and see what happens. I'll come back here as soon as I can test GNOME 42.4.

**Comment by reformit** [comment]
I'm having the same issue, anyone have a fix for it?

**Comment by reformit** [comment]
A little more info.  I looked at journalctl for gnome-shell and the following JS Error is logged when I try and move between workspaces, maybe this has something to do with it???

`JS ERROR: TypeError: list is undefined
                                       addItem@/home/brad/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceSwitcherPopupList.js:114:9
                                       _init@/home/brad/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceSwitcherPopupList.js:76:18
                                       WorkspaceSwitcherPopupList@/home/brad/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceSwitcherPopupList.js:35:4
                                       _init@/home/brad/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceSwitcherPopup.js:23:30
                                       SwitcherPopup@resource:///org/gnome/shell/ui/switcherPopup.js:34:4
                                       WorkspaceSwitcherPopup@/home/brad/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceSwitcherPopup.js:12:1
                                       _createNewPopup@/home/brad/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceManagerOverride.js:526:16
                                       _showWorkspaceSwitcherPopup/<@/home/brad/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceManagerOverride.js:437:59
                                       _showWorkspaceSwitcherPopup@/home/brad/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceManagerOverride.js:432:23
                                       _showWorkspaceSwitcher@/home/brad/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceManagerOverride.js:420:14`

**Comment by mzur** [comment]
Thanks!

@lautarodragan Can you try this, too?

**Comment by lautarodragan** [comment]
Awesome @reformit, thanks so much!

@mzur I haven't restarted yet, but I did a `Alt+F2` and `r` to restart Gnome. This would normally "disable" Workspace Matrix, but this time it didn't! 

I think we're good. I'll close this issue and reopen/comment if this happens again.
