### ISSUE TITLE
Option to show the popup until hotkeys are released

### ISSUE THREAD

**Issue by Eren121** [mzur/gnome-shell-wsmatrix#235]
I think this was the default in GNOME shell.

The popup was shown until Ctrl+Alt is released. Is it possible to have this behaviour?

Sometimes you want to see the layout, sometimes not. Waiting 500ms popup is sometimes too much, and if the time is reduced then there is no time to see the layout.

**Comment by mzur** [comment]
You get this behavior if you set the time to show the popup to 0.
