### ISSUE TITLE
Gnome 42.4 upgrade plus ws-matrix breaks login leaving system in unusable state

### ISSUE THREAD

**Issue by ElijahLynn** [mzur/gnome-shell-wsmatrix#236]
Just updated to Gnome 42.4 yesterday and it broke login. I get a system menu bar at top, but grey below that with the unability to do anything. To fix this, I had to manually power cycle with the power button, then choose Gnome Classic on X11 at the GDM login screen, which somehow disabled all the Gnome Extensions, then I logged out and logged back in with a non-classic X11/XOrg session with the extensions still disabled and login worked again. 

![PXL_20220812_185849507 (1)](https://user-images.githubusercontent.com/1504756/184426616-a1491c45-340e-41f1-87fe-43ccff731ab7.jpg)

Video of behavior w/workaround (link won't last forever though) > https://photos.app.goo.gl/ZjcaRrstywGnEcWp8

I finally figured out it was this extension causing the login hang and was able to disable it and carry-on. If I find logs I will post them.

**Comment by ElijahLynn** [comment]
```
gnome-shell[20126]: JS ERROR: TypeError: workAreaBox.get_origin is not a function
                    _computeWorkspacesBoxForState@/home/elijah/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz>
                    vfunc_allocate@resource:///org/gnome/shell/ui/overviewControls.js:199:29
```

**Comment by ElijahLynn** [comment]
I see that that function is still being called here https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/42.4/js/ui/overviewControls.js#L73-77, in 42.4. But... the latest commit is titled:

> Allocation runs every frame during the overview animations, so we want
to do as little work there as possible. Cache the work area box
computation.

https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/dc933779681fc630ee2baf87fbbc72d162d68ec6

So seems likely this commit and the caching is causing this error.

**Comment by ElijahLynn** [comment]
Linked the MR that caused this > https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2395

**Comment by mzur** [comment]
Please try #237 and report if it fixes the issue. As a workaround, you can disable this extension in the overview.

**Comment by nicjohnston** [comment]
#237 seems to have fixed the problem for me, at least on up-to-date Manjaro.  Thanks!

**Comment by ElijahLynn** [comment]
Cool, I did a:

```
cd ~/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de 
git fetch --all
git checkout g42.4-fix
```

Then enabled the extension in Extensions and it is working! Gonna reboot next after I get done with this meeting.

**Comment by ElijahLynn** [comment]
Reboot works, thank you!

**Comment by ScottGarman** [comment]
I run Manjaro and can also report that this fixes the same issue for me. Thanks @ElijahLynn for reporting this so promptly!
