### ISSUE TITLE
Add support for gnome-shell 43

### ISSUE THREAD

**Issue by tjaalton** [mzur/gnome-shell-wsmatrix#240]
Hi, upgraded my machine(s) to Ubuntu Kinetic which have GNOME 43 beta, but wsmatrix would not get loaded. Just changing metadata.json to also support 43 seems to work fine, though.

**Comment by mzur** [comment]
Could you please test all features of the extension that are available in the settings? Also maybe monitor `journalctl -f /usr/bin/gnome-shell` and see if any error messages pop up while you test the extension.

**Comment by tjaalton** [comment]
yes, all work except I can't test 'Shop popup for all monitors', since I only have one
