### ISSUE TITLE
No up/down in matrix, only left/right?

### ISSUE THREAD

**Issue by Spiritdude** [mzur/gnome-shell-wsmatrix#242]
I set 'switch-to-workspace-down' to CTRL-Down but it simply goes **right** in the matrix, I want it to go **down** in the matrix (same column, next row). The same with 'switch-to-workspace-up' goes **left**, I want it to go **up** in the matrix (same column, previous row). I made sure CTRL Up / Down aren't assigned otherwise. Yes, I restarted gnome-shell (ALT F2 'r').

Any idea what the problem or solution is?

Matrix 6x3 (Wraparound mode: None)
Ubuntu 22.04.1 LTS
Gnome 42.4

```
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Control>Up']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Control>Down']"
```

**Comment by mzur** [comment]
Does it work with the default values (`'<Control><Alt>Up'`, `'<Control><Alt>Down'`)?

**Comment by Spiritdude** [comment]
Resolved: I had another workspace related extensions enabled and interfering (skipped my attention).

Sorry for raising an issue, I spent hours to resolve strange behaviors of various extensions to get some decent functionality, when I tried wsmatrix I forgot to disable all others remotely dealing with workspaces.
