### ISSUE TITLE
Feature request: Show popup as long as Ctrl+Alt is pressed

### ISSUE THREAD

**Issue by JakobBruenker** [mzur/gnome-shell-wsmatrix#243]
Hi, love this extension, but there's one thing I wish it had: Rather than closing the popup after a configurable time, I'd like an option to have it open (as it already does) as soon as Ctrl+Alt+an arrow key is pressed, but only closed once Ctrl or Alt (or perhaps both, probably doesn't make a big difference) are released.

**Comment by mzur** [comment]
You get this behavior when you set the time to show the popup to 0.

**Comment by JakobBruenker** [comment]
Oh, perfect, thank you!
