### ISSUE TITLE
Pop-up being open prevents window movement between desktops/screen

### ISSUE THREAD

**Issue by brettins** [mzur/gnome-shell-wsmatrix#245]
**Expected Behaviour**
With the pop-up visible, while I hold Cntrl+Alt+Shift and move a window with an arrow key, I can push the arrow keys as fast as I want to and the window will move to the next desktop.

**Observed Behaviour**
When the pop-up is visible, while I hold Cntrl+Alt+Shift and move a window with an arrow key, I must wait until the pop-up has disappeared before hitting an arrow key does anything.

**Steps to reproduce**
1. Set the "Time to show the popup (ms)" setting to 3000ms or something quite long.
2. Click on the window to move
3. Hold Cntrl+Shit+Alt and press arrow keys to move the window between several desktops quickly in rapdi succession.
4. Observe that the window will not move and the view will not change desktops until the pop-up disappears.

Alternative, set the "Time to show popup (ms)" to 0 so that the pop-up does not close until the key combination is released, and observe that you cannot move the window again until you release all of the keys and press them again.

**Comment by esauvisky** [comment]
I have the same issue. Note that if you begin the workspace switching first (with ctrl+alt+arrows), and only then grab a window to move (by adding shift), it actually works properly.

systemd journal throws this error when the issue happens:
```
nov 12 17:08:10 gnome-shell[3420761]: JS ERROR: TypeError: window is null
                                      _showWorkspaceSwitcher@/home/emi/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceManagerOverride.js:391:17
                                      _keyPressHandler@/home/emi/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceSwitcherPopup.js:185:26
                                      vfunc_key_press_event@resource:///org/gnome/shell/ui/switcherPopup.js:186:18
```

**Comment by esauvisky** [comment]
@brettins I managed to fix it and made a PR. #246 fixes our problem :smile:
