### ISSUE TITLE
WSmatrix installed but stopped working

### ISSUE THREAD

**Issue by leo-stan** [mzur/gnome-shell-wsmatrix#247]
Hey hey!

I've had this extension running for years without issue, but out of the blue, it stopped working last week.

I've tried reinstalling both via `extension.gnome.org` and manually.

On `extension.gnome.org` I can toggle it on, but when I refresh the page it's still off 
![image](https://user-images.githubusercontent.com/10832754/201670882-4006a159-10f1-4e9b-8f57-dbc98fab9561.png)

I can access the settings page just fine, and save new settings. 

I'm running Ubuntu 20.04 and GNOME Shell 3.36.9

Any help would be greatly appreciated! I really like this extension :)

**Comment by mzur** [comment]
Please reopen if this is still relevant.
