### ISSUE TITLE
Hot key workspace switching overridden by workspace under mouse cursor when thumbnails active.

### ISSUE THREAD

**Issue by clottes** [mzur/gnome-shell-wsmatrix#248]
With the workspace matrix open, if the mouse is within the grid, the hotkeys for switching windows (Ctrl + Alt + direction) will then be overridden by the workspace under the mouse cursor and will return to that workspace.  This does not happen when the workspace thumbnails are not shown.
NOTE: "select workspace with mouse hover" is OFF and this still happens.

**Comment by mzur** [comment]
Please reopen if this is still relevant.
