### ISSUE TITLE
[Feature request] Option for non-grid layout (i.e. different number of column in each row)

### ISSUE THREAD

**Issue by sanjarcode** [mzur/gnome-shell-wsmatrix#254]
Is it possible to have a non-grid layout when previewing workspaces?

Example - 3 rows. where the first row has 4 workspaces (work), the second row has 2 workspaces (documentation) and the third has 4 workspaces (music player, pomodoro, communication app).
```js
x x x
x x
x x x x
```

**Comment by mzur** [comment]
No this is not possible. GNOME only supports setting the number of rows and columns.
