### ISSUE TITLE
Add NixOS installation to README.md

### ISSUE THREAD

**Issue by CamoCatX** [mzur/gnome-shell-wsmatrix#256]
According to this link: https://search.nixos.org/packages?channel=23.05&from=0&size=50&buckets=%7B%22package_attr_set%22%3A%5B%22gnomeExtensions%22%5D%2C%22package_license_set%22%3A%5B%5D%2C%22package_maintainers_set%22%3A%5B%5D%2C%22package_platforms%22%3A%5B%5D%7D&sort=relevance&type=packages&query=matrix your extension is in the nix repository, yet there is no where in the readme explaining it. Thank you

**Comment by mzur** [comment]
Please feel free to open a pull request with the change. Thanks!
