### ISSUE TITLE
Workspaces on lower rows can't be clicked in overview

### ISSUE THREAD

**Issue by ViktorNova** [mzur/gnome-shell-wsmatrix#259]
Strange behavior - I am creating vertical workspaces, let's say 4 vertical rows for this example, and 2 columns.

I can create the layout no problem, and I see the layout correctly in the Workspace overview. But I can only switch to the top row workspaces by clicking them. The lower workspaces are not clickable. Using keyboard shortcuts to switch works fine. 

Edit: in this 2 column layout, I actually can only drag move windows to another workspace via drag and drop in the overview if I'm moving them to the opposite column from the one column that  that window's workspace is currently in, but can't drop them onto the lower rows. They will only drop onto the top row. Very odd. Not sure if this is related, I'd be happy to open a new issue if not

Gnome 44
Ubuntu 23.04

**Comment by mzur** [comment]
Thanks for the report. This looks like the same issue than https://github.com/mzur/gnome-shell-wsmatrix/issues/177. Please reopen if you think otherwise.
