### ISSUE TITLE
doesn't work with shell 45

### ISSUE THREAD

**Issue by tjaalton** [mzur/gnome-shell-wsmatrix#262]
SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/shell/misc/extensionUtils.js:4:0

needs porting:
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by tjaalton** [comment]
v9.0-beta is much better, of course :)

One issue I saw with a 2x3 grid was that the animations always go horizontally, even though in reality it moved up/down.

**Comment by mzur** [comment]
Yes, that's one "feature" that had to be disabled in the beta.
