### ISSUE TITLE
Workspace thumbnails not showing in switcher popup

### ISSUE THREAD

**Issue by blainehansen** [mzur/gnome-shell-wsmatrix#264]
Hello!

When I switch between workspaces using `ctrl+alt+arrow`, the popup doesn't show thumbnails of the workspaces but only "pills" representing your position. This makes it more difficult for me to quickly navigate/understand where I am, since I'm used to having these workspace thumbnails on other machines (versions below).

The versions of the machine where thumbnails *do not* show are:
Workspace Matrix: `38` (not sure how that correlates with the versions on github)
Gnome: `42.9`
Ubuntu: `22.04.3`

For reference, the versions on the machine where thumbnails *do* show are:
Workspace Matrix: `23`
Gnome: `3.36.8`
Ubuntu: `20.04.6`

Here's a screencast showin the "pills" I'm talking about:
[Screencast from 10-11-2023 11:19:21 AM.webm](https://github.com/mzur/gnome-shell-wsmatrix/assets/5805971/5620261d-6371-4008-bf92-beac32824e22)

Here's a screenshot of the settings I've chosen for the problem machine:
![Screenshot from 2023-10-11 11-57-16](https://github.com/mzur/gnome-shell-wsmatrix/assets/5805971/642b868e-7388-47a2-8ed8-49f60750dddc)

**Comment by mzur** [comment]
Hi, please try to increase the "scale of the workspace switcher popup".

**Comment by blainehansen** [comment]
Ah hahaha thank you! I'm shocked at myself for not realizing that :man_facepalming:
