### ISSUE TITLE
settings.ui missing in 9.0

### ISSUE THREAD

**Issue by aminvakil** [mzur/gnome-shell-wsmatrix#266]
https://github.com/aminvakil/aur/actions/runs/6675838201/job/18144269432?pr=316#step:11:806

There is a command making this package which executes this:
`install -Dm644 metadata.json settings.ui *.js -t "/usr/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/"`

I don't use gnome anymore, but I want to keep this package updated in AUR, so can you please tell me if settings.ui have been removed and I should remove it from PKGBUILD, or is something wrong in 9.0?

**Comment by mzur** [comment]
Thanks for keeping the package up to date! The settings.ui file no longer exists in v9.0.

**Comment by aminvakil** [comment]
Thanks, settings.ui has been removed from PKGBUILD as well and pushed to aur.

https://aur.archlinux.org/cgit/aur.git/commit/?h=gnome-shell-extension-workspace-matrix&id=7c70436
