### ISSUE TITLE
Cosmetic issues in Gnome 45

### ISSUE THREAD

**Issue by ScislaC** [mzur/gnome-shell-wsmatrix#269]
There are a few cosmetic issues in Gnome Shell 45 that I've noticed.

1) The workspace switcher in the top bar in Gnome is no longer showing a 3x2 grid like it used to, it's now just a single row.
2) The switching animation purely scrolls sideways now, it no longer shows it moving up and down between rows.
3) There is some overlay that is incorrectly sized from the "previews" in the workspace switcher overview.

Attached is a screenshot showing issue 1 in the top-left corner and issue 3 in the middle (to the bottom right of the screen).
![matrixissues](https://github.com/mzur/gnome-shell-wsmatrix/assets/1201009/ebf93581-af7c-439b-be78-43e074533e0b)

**Comment by mzur** [comment]
Thanks for the report!

1. This is how GNOME 45 does it now. Maybe you find another extension to hide or change the display in the panel.
2. That's one of the features I had to disable until the next release of GNOME Shell (hopefully 45.1). See #263 for details.
3. That's new. I haven't seen this one before. Which distro and version do you use? Do you use other extensions?

**Comment by ScislaC** [comment]
1. That's a shame about them changing how it's displayed in the panel, thanks for the explanation. I'll definitely look about for something to disable it (or maybe someone will make an extension to offer the old style).
2. Ahhh, that's a shame. Fingers crossed 45.1 lands with the needed fix.
3. Ubuntu 23.10. Yes, I use a handful of other extensions... I will disable all of them and turn only Matrix back on and see if it works as expected. If so, I'll try flipping em on 1 at a time to see what the offender is. If not, I'll report back (I'll report back later either way).

**Comment by ScislaC** [comment]
Re: 3. Found it, Blur My Shell is causing it... figured I'd mention it just in the off chance anyone else reports it to you.

I'd close this but don't know how you want it marked. Cheers and thank you for your help!

BTW, you have 3 sponsorship links, do you have any preference on which to use?

**Comment by mzur** [comment]
Thanks for investigating 3. If you discover that there is something to be fixed in Workspace Matrix rather than Blur My Shell, feel free to open another issue.

I don't have a preference for the sponsorship links. The first two are mine. The third belongs to a contributor who helped this extension to stay afloat a while back.
