### ISSUE TITLE
Dragging window in overview snaps to top of column

### ISSUE THREAD

**Issue by Tbhesswebber** [mzur/gnome-shell-wsmatrix#273]
When I drag a window from one workspace to another in the grid overview, it always goes to the first row in the same column as the workspace that I drag it to.

For example, I have a 3x3 grid ([0,0] to [2,2]) and this chrome window in [0, 1].  In attempting to move it to [1,0], I opened the overview, dragged the window to the correct place, and released my cursor.  The window ended up in [0,0].  I subsequently tried moving it to any other workspace outside of the first row, which always resulted in it being in the first row of the workspace's column.

**Comment by mzur** [comment]
Could this be the same issue than reported in https://github.com/mzur/gnome-shell-wsmatrix/issues/177?

**Comment by Tbhesswebber** [comment]
@mzur - Was the clicking aspect of that issue already resolved?  I can click on thumbnails to navigate just fine - it's only the drag-and-drop behavior that isn't working for me.

**Comment by mzur** [comment]
The switching works if you click on a window in one of the lower workspaces but not if you click on the "background". Is this different for you?

**Comment by Tbhesswebber** [comment]
@mzur - Thanks for clarifying!  Yes, this is the same issue - closing.
