### ISSUE TITLE
Gnome 46 is coming. 

### ISSUE THREAD

**Issue by bigclap** [mzur/gnome-shell-wsmatrix#276]
There is some trouble, I can’t install extension from Gnome Store, because Ubuntu now have Gnome 46 version. Please update version)

**Comment by recolic** [comment]
Why does gnome keep breaking extension... It's so annoying. Could they have an extension standard and have old extension always working?

**Comment by andersjohansson** [comment]
Limited changes for Gonme 46 however?
https://gjs.guide/extensions/upgrading/gnome-shell-46.html

Compared to changes needed for Tactile: https://gitlab.com/lundal/tactile/-/commit/fef90c010ae5ebe10f2141b8e723af62e684c441

**Comment by mzur** [comment]
Thanks for the links, this will be helpful. I'll upgrade my work machine to Ubuntu 24.04 when it's released so for once I'll have an incentive to make the extension compatible in time :smiley: I'll get to it as soon as I can.

**Comment by g-voelker** [comment]
For everyone else who was wondering: The release date of Ubuntu 24.04 seems to be set for April 25, 2024. For everyone who is coming from a rolling release distro (like Arch or derived ones) and who has updated to Gnome 46, this extension is already disabled and will have to wait a bit.
@mzur : Thanks for the work! I love the matrix setup. So helpful when on the road with fewer screens available ^^

**Comment by mzur** [comment]
I released [v10.0-beta](https://github.com/mzur/gnome-shell-wsmatrix/releases/tag/v10.0-beta) with GNOME 46 support. Please test away and report if everything works.

**Comment by g-voelker** [comment]
Seems to work nicely on arch, thanks. Info for fellow arch users: Dashes are not supported in the pkgver so both the source archive and the PKGBUILD (pkver und checksum) have to be edited to build a clean AUR package of the beta.

**Comment by andersjohansson** [comment]
Works fine for me on arch, just through installing the released zip (`gnome-extensions install --force wsmatrix@martin.zurowietz.de.zip`).

**Comment by vladzcloudius** [comment]
> I released [v10.0-beta](https://github.com/mzur/gnome-shell-wsmatrix/releases/tag/v10.0-beta) with GNOME 46 support. Please test away and report if everything works.

Here is one issue: https://github.com/mzur/gnome-shell-wsmatrix/issues/279
