### ISSUE TITLE
Settings are not applied

### ISSUE THREAD

**Issue by mzur** [mzur/gnome-shell-wsmatrix#28]
Two [reviewers](https://extensions.gnome.org/extension/1485/workspace-matrix/) reported that the settings were applied only after a restart of GNOME. They use Ubuntu 19.04 and Pop!_OS 19.04. I wasn't able to reproduce this with Ubuntu 19.04. Is there anybody who can give more details?

**Comment by ebeem** [comment]
I have never faced this issue before, 
I use Arch Linux and I test on a fresh Ubuntu 19.04
I will check Pop!_OS 19.04 soon and let you know if anything happens.

one reviewer said `Maybe that's an issue with Gnome Shell extensions in general`
if this happens to other extensions as well, then this is not a bug in `wsmatrix`

**Comment by scottkosty** [comment]
I also cannot reproduce on Ubuntu 19.04 (just the default Desktop Environment). Everything is working smoothly here. Where are the settings stored?
