### ISSUE TITLE
drag and drop window across workspace

### ISSUE THREAD

**Issue by JE-Amouel** [mzur/gnome-shell-wsmatrix#284]
Hi,
is it possible to add a drag and drop to move windows on differente workspaces,
currently i look like moving window to another workspace within switcher popup make the window disappear.

THANKS.

**Comment by JE-Amouel** [comment]
for additional context, here is a photo edition i prepared with kritas, to show up, what it might look like,
it would be very nice if when pressing super + w shortcut,we have an immersive mode along with the scalable WS switcher pop up, it might look like activities overview.

![expo_view](https://github.com/user-attachments/assets/bcdb0260-d23f-4191-978c-1cb00c097a54)

**Comment by mzur** [comment]
Drag & drop of windows in the overview (<kbd>Super</kbd>) is discussed here https://github.com/mzur/gnome-shell-wsmatrix/pull/270. D&D of windows in the preview (<kbd>Super</kbd> + <kbd>W</kbd>) is discussed here https://github.com/mzur/gnome-shell-wsmatrix/issues/60. I'll close this as duplicate.
