### ISSUE TITLE
Add Support for GNOME 47

### ISSUE THREAD

**Issue by wirabdillah** [mzur/gnome-shell-wsmatrix#287]
GNOME 47 was released last week. Need help to update the extension.

https://gjs.guide/extensions/upgrading/gnome-shell-47.html

In my current setup, changing the metadata directly to 47 results in blank screen when pressing the windows key. But, the navigation to other workspaces still works

**Comment by mzur** [comment]
Support for GNOME 47 is discussed in https://github.com/mzur/gnome-shell-wsmatrix/pull/286

Please add your experiences/issues there.
