### ISSUE TITLE
Gnome gets slower over time

### ISSUE THREAD

**Issue by aearly** [mzur/gnome-shell-wsmatrix#290]
For many months, I had been experiencing my window manager getting slower to open new windows over time.  After a reboot, things would be snappy, but after several days running it could take several seconds to open a new window of any app (even things like save/open dialogs).

After disabling various extensions I narrowed it down to Workspace Matrix.  I think there is some sort of memory leak that causes window placement to get slower over time.

**Comment by aearly** [comment]
It's not related to workspace switching or the popup -- that always stays fast and responsive.  Only the creation of new windows becomes slow.

**Comment by mzur** [comment]
Please test if #291 fixed the issue and reopen this if not.

**Comment by aearly** [comment]
I'm still seeing slowdowns over time.  There may be another issue still at play.
