### ISSUE TITLE
clicking on any non-populated workspace in rows other than the first fails

### ISSUE THREAD

**Issue by myyc** [mzur/gnome-shell-wsmatrix#292]
might be related to #274. screencast below

[Screencast From 2024-11-18 12-05-49.webm](https://github.com/user-attachments/assets/28cbe5ce-57e2-425d-81bc-93347254a6c4)

**Comment by mzur** [comment]
Thanks! This is a duplicate of https://github.com/mzur/gnome-shell-wsmatrix/issues/177. A commit with the fix is available [here](https://github.com/mainland/gnome-shell-wsmatrix/commit/f63cf909) and should be merged with https://github.com/mzur/gnome-shell-wsmatrix/pull/270 when I find the time.
