### ISSUE TITLE
Versioning mismatch

### ISSUE THREAD

**Issue by ricardo-reis-1970** [mzur/gnome-shell-wsmatrix#293]
## What's going on with versioning?
My home:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.10
Release:	24.10
Codename:	oracular
```

This extensions lists its downloads on https://extensions.gnome.org/extension/1485/workspace-matrix/ under GNOME 47 as being version 45 or 46. When I check this repo, I get the latest as version 11.1.

Inspecting `metadata.json` from the installed version (~/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de), the listed version for the app is:
```json
  "shell-version": [
    "47"
  ],
  "version": 46
```

In the download from latest version 11.1 (from this repo), the same file states:
```json
    "shell-version": [
		"47"
    ],
    "version": -1,
```

**What's going on with versioning?** This is not merely a cosmetic question. This app has been misbehaving lately and I fear I might not be getting the latest update(s) when installing (properly?) from https://extensions.gnome.org/.

**Comment by mzur** [comment]
extensions.gnome.org has its own versioning scheme. It replaces the number in the JSON with an incrementing number of its own. The releases here at GH always have -1 as version in the JSON. But if you download the latest release here and from extensions.gnome.org, they are the same.
