### ISSUE TITLE
the latest version works but has logs spammed

### ISSUE THREAD

**Issue by icegood** [mzur/gnome-shell-wsmatrix#294]
Nov 24 18:49:31 ice-home gnome-shell[2106]: Object .Gjs_workspacePopup_workspaceThumbnail_WorkspaceThumbnail (0x60926fc4e5b0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                            == Stack trace for context 0x609269900920 ==
                                            #0   6092699f4908 i   file:///home/ice/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceSwitcherPopup.js:199 (3b368af8dd30 @ 10)
                                            #1   7fff7b029000 I   self-hosted:160 (116bb0e97f60 @ 245)
                                            #2   6092699f4878 i   file:///home/ice/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/workspacePopup/workspaceSwitcherPopup.js:199 (3b368af8dce0 @ 170)
                                            #3   6092699f47f8 i   resource:///org/gnome/shell/ui/switcherPopup.js:331 (20744be254c0 @ 12)
                                            #4   7fff7b02b160 b   resource:///org/gnome/shell/ui/environment.js:67 (116bb0e7f100 @ 98)
                                            #5   7fff7b02b8a0 b   resource:///org/gnome/shell/ui/environment.js:160 (116bb0e7f470 @ 14)
                                            #6   6092699f4768 i   resource:///org/gnome/shell/ui/init.js:21 (116bb0e70c90 @ 48)

**Comment by esauvisky** [comment]
just move the foreach above the _onDestroy():

```
_onDestroy() {
    if (this._noModsTimeoutId != 0) {
        GLib.source_remove(this._noModsTimeoutId);
        this._noModsTimeoutId = 0;
    }

    this._items.forEach((x) => x.destroy());
    this._items = [];
    
    super._onDestroy();

    while (modals.length > 0) {
        modals.pop().destroy();
    }

}
```

**Comment by mzur** [comment]
Thanks for the suggestion @esauvisky! Would you send a PR with the fix?

**Comment by esauvisky** [comment]
> Thanks for the suggestion @esauvisky! Would you send a PR with the fix?

Sure! 🙂
