### ISSUE TITLE
Popup thumbnails create trails in the bottom right corner

### ISSUE THREAD

**Issue by sanwablo** [mzur/gnome-shell-wsmatrix#295]
I'm using Gnome 46. I think I saw this reported once, but I cannot find the issue.

![Screenshot from 2024-12-11 09-55-31](https://github.com/user-attachments/assets/dbbdcf9a-7a5e-4f56-9431-d79446cf33c6)

**Comment by sanwablo** [comment]
I've just realised that this is created by an interaction with Blur My Shell.

**Comment by mzur** [comment]
Do you think this is something that could/should be fixed in this extension?
