### ISSUE TITLE
horizontal thumbnail representation in overview

### ISSUE THREAD

**Issue by brianjmurrell** [mzur/gnome-shell-wsmatrix#32]
There was a [PR](https://github.com/workspace-grid/workspace-grid/pull/67) on the [workspace-grid](https://github.com/workspace-grid/) project to optionally put the workspace thumbnails horizontally at the bottom of the overview screen.

For certain layouts, this can actually be much better use of screen real estate.

I wonder if you'd consider implementing such a feature in the workspace-matrix extension.

**Comment by mzur** [comment]
This sounds like an option for the 2D workspace list in the activities overview that is planned in #13. You are welcome to support the development there.

**Comment by brianjmurrell** [comment]
#13 is now closed as following #50.  Will #50 address this or should it be reopened?

**Comment by mzur** [comment]
You can reopen this issue if you like. #50 at its current state won't address this. In addition to that, I'm reluctant to add more and more features to this extension since that means it will be harder to maintain. Feel free to contribute to #50. Once that's finished we can see how to move forward.

**Comment by brianjmurrell** [comment]
I don't seem to have any ability to reopen a closed issue.

**Comment by mzur** [comment]
> isn't a horizontal representation just a grid of 1 row by n columns [...] but displayed along the bottom of the overview instead of the side?

Correct but #50 does not implement a switch to move the workspace list to the bottom so this issue is not addressed there. I'll reopen this issue for you.

**Comment by brianjmurrell** [comment]
> does not implement a switch to move the workspace list to the bottom

Indeed, understood.  My point was just that the "extra code" for that should be minimal.  Just a toggle and different placement code (of the grid) based on the toggle.

**Comment by mzur** [comment]
Feel free to contribute to #50. After that we can talk about extra code :wink:

**Comment by brianjmurrell** [comment]
I would but JS isn't one of the languages I am fluent in and neither is gnome-shell an environment I'm familiar with.

**Comment by ebeem** [comment]
so I checked this out, the PR you sent seems to not show the grid in a horizontal way, but rather, just displays the grid on the bottom of the screen. In other words, if you have 2 rows and 4 columns, it will look nice, but if you have 4 rows and 2 columns, it will look ugly.

the code that's used in the PR is very simple, anyone can try it out.
You need to paste this code in the `GNOME` `Looking Glass`
1- press `alt+F2` and enter `lg`
2- paste the code below and press enter in the `Looking Glass` terminal

```Javascript
let controls = Main.overview._controls;
controls._group.remove_actor(controls._thumbnailsSlider.actor);

let bin_thumbnails = new St.Bin({
    child: controls._thumbnailsSlider.actor,
    x_align: St.Align.MIDDLE
});

Main.overview._overview.add(bin_thumbnails);
```

**Comment by brianjmurrell** [comment]
Yeah, pasting that into _Looking Glass_ does put the thumbnails on the bottom, but as you say, it looks ugly with the default 1 column and (in my case) 3 rows.

Would I need #50 to switch that to 1 row and 3 columns?

**Comment by ebeem** [comment]
maybe switching rows and columns can fix it, but the ultimate solution will probably be redesigning the overview or the switcher to handle grid/matrix workspaces. Otherwise, there will always be some scenarios where the grid/matrix can't fit the overview.

if we can improve the switcher to handle all the DnD, then we will probably not need the overview to handle workspaces anymore. Check this comment for more info https://github.com/mzur/gnome-shell-wsmatrix/issues/13#issuecomment-487524588

**Comment by brianjmurrell** [comment]
> You need to paste this code in the `GNOME` `Looking Glass`
> 1- press `alt+F2` and enter `lg`
> 2- paste the code below and press enter in the `Looking Glass` terminal

It's not bad:

![2019-09-18_15-00](https://user-images.githubusercontent.com/559317/65177793-700c2500-da25-11e9-809f-9a27034c4852.png)

Clearly some significant space wastage in the display of my 3 columns X 1 row workspace configuration.

**Comment by brianjmurrell** [comment]
Any thoughts on the excessive space usage?

Other than that, I'd not see why [this solution](https://github.com/mzur/gnome-shell-wsmatrix/issues/32#issuecomment-528962898) couldn't be formalised into a knob for this extension.

**Comment by ebeem** [comment]
I think it still needs a lot of improvement before releasing it
if this is a must-feature to you, you can add it somewhere in the code for now.

**Comment by brianjmurrell** [comment]
@ebeem Could you expand?  Are you referring to the overly aggressive space use of the horizontal thumbnails or other stuff?

**Comment by ebeem** [comment]
yes, space utilization and layout management
we need to discuss a lot of issues before merging this piece of code into master, these couple of lines won't solve all cases which is going to produce more issues in the future.

For now, I see these problems in the provided solution.

1- The position of the `thumbnails box` must be set according to matrix shape.
if number of rows is greater than the number of coumns, then the default position of `thumbnails box` should be set (right). Only if the number of columns is greater than the number of rows, then we should place the `thumbnails box` at bottom.

2- The `thumbnails box`'s height should be shrunk to fit the workspaces without taking extra space (this problem exists in the extension right now, but it's the default `GNOME` behavior and it does not look so weird when placed on the right).

**Comment by brianjmurrell** [comment]
@ebeem I disagree with point #1.  I think the position of the box is more an artefact of the physical screen dimensions, not the workspace layout.  But that is just my opinion, which differs to yours.  That suggests to me that this is going to be subjective and probably just needs a user-toggle knob to let the user decide which he likes best.

I think your point number 2 is just re-iteration of my observation of the space usage/wastage, yes?

**Comment by ebeem** [comment]
yeah, the screen dimensions is probably another factor that we will have to consider before deciding the position of thumbnails box, I think we can just keep the default right position and allow users to change the behavior in preferences to top/right/bottom/left as you said.

yes, the observation is the same. Please feel free to add any other points or comments so we create a list of tasks for this feature in case someone is willing to contribute.

**Comment by brianjmurrell** [comment]
In all honesty, my only (minor enough that I use it as is) issue is the extra space below my 3 horizontally configured workspaces in the thumbnails.

**Comment by JoeKays** [comment]
So for everyone asking for a solution for only one row of horizontally configured workspaces here is my solution:

in _OverviewOverride.js_:

add the following import at the top:

    const { St } = imports.gi;

add the following (note the 150 for the height of 1 single row)
in line 75 at the end of function _\_activateOverride()_:

    let controls = Main.overview._controls;
    controls._group.remove_actor(controls._thumbnailsSlider.actor);
    this._bin_thumbnails = new St.Bin({
         child: controls._thumbnailsSlider.actor,
         x_align: St.Align.MIDDLE,
         height: 150
      });

    Main.overview._overview.add(this._bin_thumbnails);

add the following
in line 83 at the end of function _\_deactivateOverride()_:

    let controls = Main.overview._controls;
    Main.overview._overview.remove_actor(this._bin_thumbnails);
    this._bin_thumbnails.remove_actor(controls._thumbnailsSlider.actor);
    controls._group.add(controls._thumbnailsSlider.actor);

I would be glad if anyone more familiar with gnome-shell extensions improved the code further and made it available through a commit or similar...

**Comment by JoeKays** [comment]
Note: this doesn't seem to persist after standby.
If anyone knows a solution to that problem that'd be helpful!

**Comment by brianjmurrell** [comment]
@JoeKays Suggestion works here.  I noted that 150 was too small and increased it to 450.  Better.  There's still space wastage under the row of thumbnails at the bottom though.

Still better than the wastage on the side of a monitor in portrait orientation.

**Comment by ebeem** [comment]
@JoeKays figuring out how we can make it persists after suspend is not hard, I can look that up when I have some time. The `height: 150` idea is great, but we need to somehow match it with the thumbnail height and number of rows we have, this will need to take care of spacing between thumbnails as well.

@brianjmurrell has a portrait-oriented monitor, this makes his thumbnail size totally different than what we usually get in normal cases.

so assuming the height of each thumbnail = `150`
and spacing between thumbnails = `10`
and number of rows = `3`

`(num_rows * thumbnail_height + (num_rows - 1) * spacing)`
total height will be `(3 * 150 + (3-1) * 10)`

I think in most cases we will have `num_rows = 1` for this case, which means we have a vertical layout, but I am suggesting we use this solution later to make the position of the workspace in overview option `(right|left|top|bottom)`

**Comment by brianjmurrell** [comment]
@JoeKays hack in https://github.com/mzur/gnome-shell-wsmatrix/issues/32#issuecomment-578402593 doesn't seem to work on the latest version.  It results in no workspace thumbnails, just thumbnails for the windows in the current workspace.

**Comment by mzur** [comment]
I'll close this issue as we don't plan to implement such a feature here. Custom implementations can be maintained in a fork.
