### ISSUE TITLE
Please provide installation instructions in `README.md`.

### ISSUE THREAD

**Issue by noel-yap** [mzur/gnome-shell-wsmatrix#34]
Those new to GNOME extensions won't know what to do with the `.zip` file. Please provide instructions.

**Comment by ebeem** [comment]
I think the .zip file is not meant for those who are new to GNOME. getting the extension from gnome extensions website is the way to go.

![test](https://user-images.githubusercontent.com/25146039/58522005-350c8a00-81c7-11e9-9de2-faa39210c904.png)
https://extensions.gnome.org/extension/1485/workspace-matrix/

**Comment by mzur** [comment]
@ebeem is right but I think we can add an installation section to the readme to make this more clear.
