### ISSUE TITLE
How to bring up explicitly the workspace switcher?

### ISSUE THREAD

**Issue by noel-yap** [mzur/gnome-shell-wsmatrix#35]
There are times when I would like to bring up the workspace switcher then decide which workspace to switch to. Is there a way to bring it up (without first switching workspaces) then take my time to use it to choose the workspace to switch to?

**Comment by mzur** [comment]
No. This could be done with the "workspace overview" which is planned [here](https://github.com/mzur/gnome-shell-wsmatrix/issues/13) but we still need to find someone who is willing to implement it.
