### ISSUE TITLE
How to configure wraparound?

### ISSUE THREAD

**Issue by noel-yap** [mzur/gnome-shell-wsmatrix#36]
`README.md` indicates wraparound can be turned on. How is this done?

**Comment by ebeem** [comment]
use the [gnome-tweaks](https://gitlab.gnome.org/GNOME/gnome-tweaks) tool to change the preferences of the extension

![Screenshot from 2019-06-03 23-15-45](https://user-images.githubusercontent.com/25146039/58831534-8f896880-8655-11e9-8c19-994f40e97c2a.png)

**Comment by noel-yap** [comment]
Hmm, I must not have the latest installed (I'm seeing only `Number of columns`, `Number of rows`, and `Scale of workspace thumbnails`). How do I go about forcing the installation of the latest release?

**Comment by ebeem** [comment]
you can find that in the `readme` file
the most preferred way is to download/update from [GNOME Shell Extensions](https://extensions.gnome.org/extension/1485/workspace-matrix/) website

**Comment by mzur** [comment]
This only works with GNOME 3.30 and above. We haven't backported the new features to GNOME 3.28.
