### ISSUE TITLE
Changing wraparound mode

### ISSUE THREAD

**Issue by kirillt** [mzur/gnome-shell-wsmatrix#38]
This is an awesome extension, works as expected.

There is a line in the description about wraparound modes:
> Two wraparound modes for navigating workspaces (optional).
But I don't see any control in GNOME Extensions menu for changing this mode.

Is it supported only via manual tweaking in source code?
Wraparound is really fun feature, would be glad to enable it.

**Comment by mzur** [comment]
This can be done in the settings of the extension (see the screenshot [here](https://github.com/mzur/gnome-shell-wsmatrix/issues/31#issuecomment-492221220)). However, it only works with GNOME 3.30 or higher. Newer features have not been backported to GNOME 3.28.

**Comment by kirillt** [comment]
@mzur thanks, now it's clear.
I need to upgrade my GNOME.
