### ISSUE TITLE
Moving within matrix

### ISSUE THREAD

**Issue by dodiak** [mzur/gnome-shell-wsmatrix#39]
How to move within the matrix in 2D mode and node in 1D. I would like to move the same way as in older grid. So Up in the matrix should go up and not to the left. The same way Down. Or am I missing something? Thanks.

**Comment by mzur** [comment]
Please check your GNOME version. Maybe you are affected by a [bug](https://github.com/mzur/gnome-shell-wsmatrix/issues/4) in GNOME 3.30.

**Comment by dodiak** [comment]
I am on 3.30. What can I do about?

**Comment by mzur** [comment]
You can [manually patch your version of Mutter](https://github.com/workspace-grid/workspace-grid/issues/88#issuecomment-435037672) or upgrade to a newer version of GNOME.

**Comment by dodiak** [comment]
> You can [manually patch your version of Mutter](https://github.com/workspace-grid/workspace-grid/issues/88#issuecomment-435037672) or upgrade to a newer version of GNOME.

Great! It does work. Thank you :)
