### ISSUE TITLE
Matrix mode does not work correctly in GNOME 3.30

### ISSUE THREAD

**Issue by dessasin** [mzur/gnome-shell-wsmatrix#4]
when I used to use GNOME 3.28, the plugin was working literally, so I could switch between the virtual desktops as left and right, but now I can only move up and down as in standard gnome settings.you can find the video about the problem at the link below.

[Screencast](https://streamable.com/afzvl)

**Comment by mzur** [comment]
This looks like the Mutter bug discussed in #2. You can try to build your own patched version of Mutter (see [here](https://github.com/zakkak/workspace-grid/issues/88#issuecomment-435037672)) or wait for the official release.

**Comment by dessasin** [comment]
Thank you very much, mutter application re-compiled and installed and solved the problem.By the way, your plugin is very nice and I wish you success in your work.

**Comment by mzur** [comment]
Thanks! Glad to hear you like the plugin.

**Comment by harish2704** [comment]
@mzur : I just reported this mutter bug on their bug tracker. https://gitlab.gnome.org/GNOME/mutter/issues/409

I hope this is necessary because, the bug is still not resolved in the upstream . Right ?

**Comment by fvdnabee** [comment]
The fix has been included in mutter 3.31.2, but this seems to be a developer release. According to https://www.phoronix.com/scan.php?page=news_item&px=GNOME-Shell-Mutter-3.31.2 we'll have to wait until March for 3.32 to be released.
