### ISSUE TITLE
Touch screen 'four fingers' switch workspace gesture works like native dynamic mode

### ISSUE THREAD

**Issue by esauvisky** [mzur/gnome-shell-wsmatrix#40]
Title is quite self explanatory, when swiping with four fingers to switch workspaces on a touchscreen monitor, the behaviour is exactly the same as the old one, i.e.: the dynamic thing.

This is totally not critical, but would be a nice attention to detail a for a future release!

**Comment by mzur** [comment]
Unfortunately I don't have a screen to test this with. Can you please elaborate? Can you move horizontally between workspaces? Are new workspaces added although the number should be fixed?

Please feel free to start working on this. I'm not sure if this is is an issue with GNOME or with this extension. In case of the latter, the [`_showWorkspaceSwitcher`](https://github.com/mzur/gnome-shell-wsmatrix/blob/1c9c48c16b8d9ebf85df418bc3098471d2830f74/wsmatrix%40martin.zurowietz.de/WmOverride.js#L220) function might be a good place to start.

**Comment by ElijahLynn** [comment]
Just browsing this issue queue now due to an unrelated issue and just learned about the 4 finger switch feature from this issue! Love that it is built into Gnome!

The 4 finger gesture works for me but only horizontally, on the current row of my 3 x 3 grid I have setup. It does not work vertically to get to the other rows. I can post a video if you like.

**Comment by mzur** [comment]
@ElijahLynn Feel free to tinker with the [`_showWorkspaceSwitcher`](https://github.com/mzur/gnome-shell-wsmatrix/blob/1c9c48c16b8d9ebf85df418bc3098471d2830f74/wsmatrix%40martin.zurowietz.de/WmOverride.js#L220) function to find out why vertical switching is not possible. Basic debugging can be done with `log('some string', someObject)` and `journalctl -f /usr/bin/gnome-shell`.

**Comment by aminvakil** [comment]
Four fingers on touchpad doesn't work either, although I don't know if it has to do something with gnome 3.36 or not, I used version 2.2.0 on gnome 3.34 and has just updated to 3.0.1.

**Comment by mzur** [comment]
@aminvakil You could check if you can switch workspaces with four fingers if this extension is disabled. If it works, you can also try to find out why it doesn't work for this extension.

**Comment by aminvakil** [comment]
@mzur It doesn't work without extension as well. I couldn't figure out why, but it doesn't have to be on this issue, thanks.

**Comment by mzur** [comment]
Please check if this issue still exists in GNOME 40. If yes, please reopen.
