### ISSUE TITLE
how to restart on Debian-10

### ISSUE THREAD

**Issue by mfrasca** [mzur/gnome-shell-wsmatrix#42]
the front page suggests `Alt-F2` and then the command `r`.
on Debian-10, with the default user interface, I get:
![image](https://user-images.githubusercontent.com/122869/62067241-e005e800-b1f8-11e9-885f-63dd61aa5f34.png)

**Comment by mzur** [comment]
Looks like you need to [log out and back in](https://unix.stackexchange.com/a/447020/95089) on Wayland. If you plan to develop this extension, I suggest you use a VM to test the extension and code on the host machine. This way you don't have to re-open the editor all the time.

**Comment by mfrasca** [comment]
11ab5b8 closes this.
