### ISSUE TITLE
Support for dual monitors in preview thumbnails

### ISSUE THREAD

**Issue by josephrocca** [mzur/gnome-shell-wsmatrix#46]
This issue is mainly an excuse to say thanks for all your work on this! Happy to throw you a few coffees if you have Patreon or something like that.

Dual monitor thumbnails would obviously make the thumbnail grid twice as wide, which isn't ideal, but would be better for me than not being able to see my other monitor in the preview. Not sure how hard this would be to implement - feel free to close if it's not on the roadmap! It's really just an "icing on the cake" feature - not super important.

Thanks again!

**Comment by mzur** [comment]
Thanks, good to hear that people find the extension useful. @ebeem started to work on multi monitor support a while ago ( #21 ). Feel free to start working on this again. I probably won't be able to develop new features anytime soon.

**Comment by ebeem** [comment]
@josephrocca  you can try the PR #49 and report any problem you find if you're interested in this feature.
Thanks.

**Comment by josephrocca** [comment]
Awesome! I'll definitely be giving this a shot in the next few days when I get a chance and will report back with results.

**Comment by mzur** [comment]
This discussion can continue in #49.
