### ISSUE TITLE
[Feature] Change keyboard shortcut to move between workspaces

### ISSUE THREAD

**Issue by GuillaumeLeGoc** [mzur/gnome-shell-wsmatrix#47]
GNOME keyboard shortcuts allows only to edit the shortcut to switch workspace in the vertical direction (one workspace below, one workspace top) and it works fine with WSMatrix, but I can't change the default shortcut to move one workspace right/left (which is ctrl+alt+left/right arrow). I'd like to be able to change this to something else.

**Comment by mzur** [comment]
You can do this with `gsettings`. Run `gsettings list-keys org.gnome.desktop.wm.keybindings` to get a list of relevant keys that can be configured, e.g. `switch-to-workspace-left`. Get the current value with: `gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-left`. Set the value with `gsettings set`.

**Comment by GuillaumeLeGoc** [comment]
> You can do this with `gsettings`. Run `gsettings list-keys org.gnome.desktop.wm.keybindings` to get a list of relevant keys that can be configured, e.g. `switch-to-workspace-left`. Get the current value with: `gsettings get org.gnome.desktop.wm.keybindings switch-to-workspace-left`. Set the value with `gsettings set`.

**Comment by GuillaumeLeGoc** [comment]
Great, this worked. I used the dconf editor though. Maybe you could mention the location `org.gnome.desktop.wm.keybindings` in the README.
Thank you for your time!

**Comment by mzur** [comment]
I'll close this then. I'll consider adding a note to the readme if more people ask about it.

**Comment by gschaffner** [comment]
This would be an excellent addition to the README, I think! I was surprised to find that this is the first issue asking about changing keybindings in this repo.

**Comment by oscar-corredor** [comment]
I second this, it took me longer than needed to find out that this can be changed.

**Comment by udnaan** [comment]
The settings were not available in my schemas my default (ubuntu 18.04). The following fixed it:

```
$ sudo cp ~/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/schemas/org.gnome.shell.extensions.wsmatrix.gschema.xml  /usr/share/glib-2.0/schemas/
$ sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```

**Comment by Anamitr** [comment]
Definitely could use a note about this in Readme

**Comment by mzur** [comment]
@Anamitr [There is](https://github.com/mzur/gnome-shell-wsmatrix#known-issues).

**Comment by mzur** [comment]
There is now a new [wiki page](https://github.com/mzur/gnome-shell-wsmatrix/wiki/Custom-keyboard-shortcuts) on keyboard shortcuts.

**Comment by victor-ca** [comment]
in case someone looks for it: to make it work like in windows (ctrl+win+arrows)
```sh 
gsettings set  org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Control><Super>Right']" 
gsettings set  org.gnome.desktop.wm.keybindings switch-to-workspace-left  "['<Control><Super>Left']" 
```

**Comment by elvisgiv** [comment]
> in case someone looks for it: to make it work like in windows (ctrl+win+arrows)
> 
> ```shell
> gsettings set  org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Control><Super>Right']" 
> gsettings set  org.gnome.desktop.wm.keybindings switch-to-workspace-left  "['<Control><Super>Left']" 
> ```

and

gsettings set  org.gnome.desktop.wm.keybindings switch-to-workspace-up  "['<Control><Super>Up']"
gsettings set  org.gnome.desktop.wm.keybindings switch-to-workspace-down  "['<Control><Super>Down']"
