### ISSUE TITLE
gnome-shell crashes when we reload gnome shell

### ISSUE THREAD

**Issue by harish2704** [mzur/gnome-shell-wsmatrix#5]
restarting gnome shell ( <Alt-f2> r ) on xserver session will crash gnome shell if we are using this extension.

This bug look like a upstream bug because, it affects  `workspace-grid` extension also . https://github.com/zakkak/workspace-grid/issues/106

we need to file a proper bug report on upstream to resolve this issue.

**Comment by mzur** [comment]
Thanks for investigating this bug. In your bug report you conclude:

> failure to compute `current_workspace_index` can be due to wrong calculation done by workspace-grid extension or due to some API change in mutter.

Do you think this issue needs to be fixed on the part of this extension or in Mutter?

**Comment by harish2704** [comment]
@mzur I am still not 100% sure about this conclusion. 
As per my last experiment result, my previous statement ( the one you quoted  ) is not correct.

Fact is , I am very new to gnome shell extension development and its internals.
 I think, an experienced developer can either find the root cause of the bug  or we can at least describe this bug in a proper way to the upstream project ( gnome-shell or mutter )

( I am still not in a position to at least  describe the bug properly to upstream project. )

**Comment by mzur** [comment]
I'll close this for now. Please feel free to reopen if you have any updates on this.
