### ISSUE TITLE
[Feature Request]: switching within a workspace instead of across when Alt+Tab or Alt-` is used

### ISSUE THREAD

**Issue by GuruMulay** [mzur/gnome-shell-wsmatrix#51]
First of all I really like this extension, thanks! 
This is to request a feature similar to what we had in Ubuntu 16.04 workspaces wherein the Alt+Tab or Alt+\` keys switched the windows within the workspace as opposed to jumping (switching) around across the workspace. Seems like this 'issue' is also there with the default `dynamic` or `static` workspaces of 18.04.
Thanks for this great extension!

**Comment by mzur** [comment]
You can do this already with a custom keyboard shortcut. See [here](https://askubuntu.com/a/996410/281685) for more information.

**Comment by GuruMulay** [comment]
Thanks @mzur, closing the issue.
