### ISSUE TITLE
[Feature] Isolated Workspaces

### ISSUE THREAD

**Issue by Haberkamp** [mzur/gnome-shell-wsmatrix#53]
It would be cool if you can switch the workspaces on every monitor individually.

Imagine you have two monitors. On the primary monitor you have your code editor opened and on the secondary monitor you have your web browser open. And now you change the workspace on the secondary monitor and you still can see your code editor on the primary monitor.

**Comment by mzur** [comment]
Do you know of the "Display Handling" settings of GNOME Tweaks? There you can activate "Workspaces on primary display only". This will show the same window on the secondary monitor for all workspaces on the primary monitor.

If you already know this, I have to say that I don't think this feature fits to the scope of this extension. This extension focuses on providing a grid of workspaces (in contrast to a column/row) and should not become a general "enhanced workspaces" extension.

**Comment by Haberkamp** [comment]
Ok, well then will just close this issue. But thanks anyway. 👋
