### ISSUE TITLE
Border not correctly shown In Gnome 3

### ISSUE THREAD

**Issue by Koldar** [mzur/gnome-shell-wsmatrix#54]
### Problem

Orange border for current visualized workspace is not shown correctly. in the main project readme the border is shown to be thick blue, but on my computer thge border is partially shown, namely only the left part of the border is shown and such part is displayed in orange.
I expected to have a rectangular border, much like the one displayed in the main project readme.

**Expected**
![expected](https://raw.githubusercontent.com/mzur/gnome-shell-wsmatrix/master/preview.png)

**Actual**
![Screenshot from 2019-09-18 08-53-51](https://user-images.githubusercontent.com/6443614/65123142-ed6a7200-d9f2-11e9-8c96-f6c3b714fd34.png)

### Additional information

**lsb_release -a**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

**uname -a**
```
Linux tesla 5.0.0-27-generic #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**~/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/metadata.json**
```
{
"_generated": "Generated by SweetTooth, do not edit", 
  "description": "Arrange workspaces in a two dimensional grid with workspace thumbnails.\n\nIN CASE OF ERROR AFTER UPDATE:\nPress Alt+F2 and run the \"r\" command to restart GNOME.", 
  "gettext-domain": "wsmatrix", 
  "keybindings-schema": "org.gnome.shell.extensions.wsmatrix-keybindings", 
  "name": "Workspace Matrix", 
  "settings-schema": "org.gnome.shell.extensions.wsmatrix-settings", 
  "shell-version": [
    "3.32"
  ], 
  "url": "https://github.com/mzur/gnome-shell-wsmatrix", 
  "uuid": "wsmatrix@martin.zurowietz.de", 
  "version": 15
}
```

**/usr/share/gnome/gnome-version.xml**
```
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>32</minor>
 <micro>1</micro>
 <distributor>Ubuntu</distributor>
 <!--<date></date>-->
</gnome-version>
```

**Comment by mzur** [comment]
This depends on the theme that you are using and is not controlled by this extension. The theme of the screenshot is [Numix-Complement](https://github.com/mzur/Numix-Complement) which was derived from [Numix](https://github.com/numixproject/numix-gtk-theme). At some point you might be able to adjust the color of the indicator with this extension, though ( #12 ).

**Comment by Koldar** [comment]
I see,

Maybe to avoid confusion it would be best to be put in the readme, something that allows people to be directed to Numix-Complement. When I saw the border I thought of a unexpected behaviour.

Thanks for the clarification (you can close if you want)
