### ISSUE TITLE
Switching workspace horizontally on overview scrolls windows vertically

### ISSUE THREAD

**Issue by tom-james-watson** [mzur/gnome-shell-wsmatrix#56]
Love the new overview grid layout!

This is probably easiest to explain with a video: https://streamable.com/fbi70

I have a 2x3 grid. Switching workspaces left and right whilst in the overview will scroll the open windows on/off the screen vertically, as opposed to the expected horizontally.

I get the feeling this is just a limitation of gnome. However, as a horizontal workspace switch whilst *not* in the overview will correctly animate horizontally, I was wondering whether this can be fixed.

**Comment by mzur** [comment]
I'm not sure if this behavior can be changed. Maybe only with some extensive override of the activity overview. I'm leaving this open for anyone who wants to look into this (even if you only find that it's not possible for an extension to change the animation).

**Comment by ebeem** [comment]
I looked at this, the function `_updateWorkspaceActors` in `WorkspacesView` is responsible for animating the workspaces in the overview. I already made it animate workspaces the expected way (similar to `workspaces-switcher` popup). I will submit a PR once the little problem in #57 is fixed.

**Comment by tom-james-watson** [comment]
Amazing - looking forward to it!

**Comment by mzur** [comment]
Maybe this is easier to implement for GNOME 3.34 as it seems to have support for horizontal workspaces?

**Comment by tom-james-watson** [comment]
Oh so it looks like this might actually just fix itself once that is released

**Comment by ebeem** [comment]
I am already on `GNOME 3.34`, instead of workspaces being scrolled vertically, they are scrolled horizontally now. but not both as needed.

**Comment by mzur** [comment]
But at least the appropriate animation logic should be available, right?

**Comment by ebeem** [comment]
just a matter of providing `x & y` values to `Tweener`
in `3.34` it provides `x` only
prior to `3.34` it provided `y` only

**Comment by ebeem** [comment]
please test #70 and provide your feedback.
we can continue the discussion in #70 if any further improvements are needed.
