### ISSUE TITLE
Backward compatibility (GNOME 2.28)

### ISSUE THREAD

**Issue by EmmanuelMess** [mzur/gnome-shell-wsmatrix#58]
I see a steep visual difference between moving from one  one workspace to another in Unity vs gnome-shell-wsmatrix.

Ubuntu 18.04
Intel® Core™ i3-6100 CPU @ 3.70GHz × 4 
Intel® HD Graphics 530 (Skylake GT2)
Gnome 3.28.2

**Comment by ebeem** [comment]
There's an option for caching in the preferences, I don't think this option is available for `Gnome 3.28` since a lot of the new features are only maintained in the latest `Gnome` version. So I think you will notice a large difference in performance if u upgrade to `Gnome 3.32` and update the extension.

**Comment by EmmanuelMess** [comment]
> So I think you will notice a large difference in performance if u upgrade to Gnome 3.32 and update the extension.

I think so too, but I don't think I can update without changing ppa.

**Comment by tom-james-watson** [comment]
Yeah - this sounds like a performance issue. There have been many performance and animation smoothness improvements since 18.04. If you're sticking to LTS, you'll probably need to wait till 20.04 to see the improvements.

**Comment by ebeem** [comment]
I agree with @tom-james-watson. I know this is not a solution for your problem, but maintaining older versions of GNOME is a time-consuming task. I hate to tell you this, but unless someone is willing to invest some time and implement some backward compatibility, this issue will probably not be fixed.

**Comment by EmmanuelMess** [comment]
:disappointed:

**Comment by ebeem** [comment]
I changed the title to reflect the issue, will leave this issue open in case anyone is willing to contribute.

**Comment by mzur** [comment]
I'm using Ubuntu 18.04 with GNOME 3.28 myself and I only backported the features that were important for me personally. I'm not planning to backport any new features but I'm open for contributions.

**Comment by mzur** [comment]
I decided that anyone who wants to have backward compatibility should create their own fork of this extension. Ubuntu 20.04 LTS is right around the corner and will be supported with all features. Users of 18.04 can upgrade then.
