### ISSUE TITLE
Pop OS 18.10

### ISSUE THREAD

**Issue by mathewjpotter** [mzur/gnome-shell-wsmatrix#6]
It doesn't appear to activate when I try and install on POP OS, tried restarting logging and logging out, but only see the normal verticle grid when pressing super +s

thanks

**Comment by mathewjpotter** [comment]
mp@pop-os:~$ sudo journalctl /usr/bin/gnome-shell

-- Logs begin at Tue 2018-12-18 10:59:26 MST, end at Tue 2018-12-18 12:40:26 MST. --
Dec 18 10:59:33 pop-os gnome-shell[1493]: g_dir_open_with_errno: assertion 'path != NULL' failed
Dec 18 10:59:33 pop-os gnome-shell[1493]: g_filename_to_utf8: assertion 'opsysstring != NULL' failed
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: Did not find color property '-barlevel-overdrive-color'
Dec 18 10:59:33 pop-os gnome-shell[1493]: Did not find color property '-barlevel-overdrive-color'
Dec 18 10:59:33 pop-os gnome-shell[1493]: Did not find color property '-barlevel-overdrive-color'
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 29]: ref
Dec 18 10:59:33 pop-os gnome-shell[1493]: Did not find color property '-barlevel-overdrive-color'
Dec 18 10:59:33 pop-os gnome-shell[1493]: Did not find color property '-barlevel-overdrive-color'
Dec 18 10:59:33 pop-os gnome-shell[1493]: Did not find color property '-barlevel-overdrive-color'
Dec 18 10:59:33 pop-os gnome-shell[1493]: Did not find color property '-barlevel-overdrive-color'
Dec 18 10:59:33 pop-os gnome-shell[1493]: Did not find color property '-barlevel-overdrive-color'
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported
Dec 18 10:59:33 pop-os gnome-shell[1493]: + combinators are not supported

**Comment by mzur** [comment]
This extension does not change the overview that appears on `Super+S`. But it *does* rearrange the workspaces. You can see it in action if you press `Super+<Arrow key>`. I just tested it with a fresh install of Pop OS and it works. However, it seems to be affected by the Mutter bug that is discussed in #4.

**Comment by mathewjpotter** [comment]
silly me, I missed that .I very much appreciate the work you did on this plugin. is there a way to show a preview? similar to super+s

**Comment by mzur** [comment]
You get the preview thumbnails in the workspace switcher that pops up whenever you change the workspace. But I don't plan to change the `Super+S` overview with this extension. I think it would take up too much space there. If you really want this you can try the [Workspace Grid](https://github.com/zakkak/workspace-grid) extension.

**Comment by mzur** [comment]
I'll close this for now. Please reopen if this is still relevant.
