### ISSUE TITLE
Key combination error

### ISSUE THREAD

**Issue by dessasin** [mzur/gnome-shell-wsmatrix#62]
Although the plugin's default key combinations work normally, they interfere with my personal key combinations.I made a video that explains the problem better

Screencast: [https://streamable.com/e5og8](https://streamable.com/e5og8)

Distro: Pop Os 19.04
Kernel: 5.0.0.31
Gnome Version: 3.32.2

**Comment by ebeem** [comment]
what is exactly the key combination that conflicts with your personal combination?
is it `super+w`?

**Comment by dessasin** [comment]
Yes,my window closing key combination is ctrl+w
