### ISSUE TITLE
open windows move to different workspace after locking the screen

### ISSUE THREAD

**Issue by nkoroste** [mzur/gnome-shell-wsmatrix#64]
When leaving my machine I typically lock it. After coming back and unlocking the machine all windows in workspace one row up from (2, 1) and (2, 2) move to (1,1) and (1,2)

**Comment by ebeem** [comment]
check this comment https://github.com/mzur/gnome-shell-wsmatrix/issues/29#issuecomment-516789433
this was fixed in `v2.3.0`, let us know if you have an up to date version and you applied the workaround and this is still not working.

**Comment by mzur** [comment]
Maybe you need to set your workspaces to "static" to fix this (see [here](https://github.com/mzur/gnome-shell-wsmatrix/issues/29#issuecomment-519180764)).

**Comment by nkoroste** [comment]
Not sure which version I'm running since it's not obvious to check but installed it yesterday via the GNOME Shell Extensions website.

So far the workaround seemed to work. I think the key point was to turn **off the extension before** modifying setting in the workspace tab.

I would recommend to add these instruction to the top level readme file.

**Comment by mzur** [comment]
Done.
