### ISSUE TITLE
Is there a way to make visual indication of active workspace more prominent in grid view?

### ISSUE THREAD

**Issue by nrvale0** [mzur/gnome-shell-wsmatrix#66]
I'm not sure if this falls under the auspices of the extension or of the desktop theme but I'd like to have a bit more visual indication of the current workspace when in grid overview mode. As it currently stands I just get a colored bar down the left hand side of the active workspace and its quite hard to pick out quickly and reliably. Might be as simple as coloring the entire outside diameter of the active workspace.

(see screenshot)

![Untitled](https://user-images.githubusercontent.com/3616282/66784991-cf2c5080-ee90-11e9-8051-23e23900e598.jpg)

**Comment by mzur** [comment]
This is related to #12. There we concluded that the general appearance of the indicator should be controlled by the theme. We agreed to implement a color chooser in case the indicator can't be distinguished from the background of the workspace popup. But that's it. I don't want this extension to become too complicated to maintain.

**Comment by nrvale0** [comment]
Closing and will follow #12. Thx
