### ISSUE TITLE
Showing grid on overview crashes gnome shell on 19.10

### ISSUE THREAD

**Issue by tom-james-watson** [mzur/gnome-shell-wsmatrix#69]
If you check "Show workspace grid in the overview" on Ubuntu or Pop!_OS 19.10, bringing the overview up will completely crash gnome shell.

This seems reproducible on a fresh install.

**Comment by AlwinEgger** [comment]
This is due to lack of Gnome 3.34 support. Ubuntu 19.10 migrated to this version.

**Comment by ebeem** [comment]
you can test #57 and provide your feedback.
Thanks for reporting.
