### ISSUE TITLE
Doesn't save new values in settings after inputs blur (unfocus)

### ISSUE THREAD

**Issue by AlexWayfer** [mzur/gnome-shell-wsmatrix#7]
There is 3 by default. I'm changing to 2. And nothing happens. There is 3 again after closing and opening the configuration window.

**Comment by mzur** [comment]
Please tell me which operating system (and version) and which GNOME shell version you use.

**Comment by AlexWayfer** [comment]
Arch Linux, GNOME 3.30.2

**Comment by mzur** [comment]
Sorry but I wasn't able to confirm this with a fresh install of Ubuntu 18.10 and GNOME 3.30.2. Do you get any error output while you change the settings when you monitor `journalctl -f /usr/bin/gnome-shell`?

**Comment by AlexWayfer** [comment]
> Do you get any error output while you change the settings when you monitor journalctl -f /usr/bin/gnome-shell?

No.

> Sorry but I wasn't able to confirm this with a fresh install of Ubuntu 18.10 and GNOME 3.30.2.

Record: https://drive.google.com/file/d/13ClZLWTh-6XlBPeLtlEzTFqMwolTDzJH/view?usp=sharing

**Comment by mzur** [comment]
I see. I think this is an issue with the event handling of the input element. Try the '+' and '-' buttons, it should work then. I'll have a look at this.

**Comment by AlexWayfer** [comment]
> Try the '+' and '-' buttons, it should work then.

Yep, that works. Thank you.

**Comment by mzur** [comment]
This should be fixed with the latest release. It will be available through extensions.gnome.org in the next weeks.

**Comment by AlexWayfer** [comment]
Thank you very much!
