### ISSUE TITLE
Problems with Workspace matrix in Ubuntu 19.10 with Gnome 3.34.1

### ISSUE THREAD

**Issue by richardquint** [mzur/gnome-shell-wsmatrix#71]
I've been using the  Workspace matrix and Workspace Indicator extensions with no problems in Ubuntu19.04 with Gnome 3.32.1.  In a fresh install of 19.10 with 3.34.1 Workspace matrix fails to display the chosen 2x2 grid, rather it shows a single column. In addition if I run it with Workspace Indicator it replaces the Workspace Indicator panel object with its own indicator (a row of four workspaces), something new since 19.04. If I turn off Workspace matrix, Workspace Indicator works properly.

**Comment by ebeem** [comment]
where does it fail to show the grid? in `gnome-overview` or the `switcher-popup`?
I have just tried installing `Workspace Indicator`, I haven't faced any issues at all.
of course `workspace indicator` displayed a row of workspaces, but `wsmatrix` worked well

can you try cloning master or downloading the latest release? I think it will take time for `gnome-extensions` to release the new version, the current version available in `gnome-extensions` does NOT fully support `gnome 3.34`

**Comment by richardquint** [comment]
Perhaps it's easier to see if I post screenshots illustrating what I've written.  I have tried restarting Gnome shell, logging out and in again and even rebooting.  I'll try downloading the latest release next.
![19 04 after click on Activities](https://user-images.githubusercontent.com/39503532/67626565-b19ca680-f801-11e9-97f7-5fe3bd641b76.png)
![19 10 with Workspace matrix not activated](https://user-images.githubusercontent.com/39503532/67626567-b8c3b480-f801-11e9-8418-f514d3b45a60.png)
![19 10 with Workspace matrix activated](https://user-images.githubusercontent.com/39503532/67626568-bd886880-f801-11e9-8daf-6fdc57f9b873.png)
![19 10 with Workspace matrix activated after clicking on Activities](https://user-images.githubusercontent.com/39503532/67626569-c0835900-f801-11e9-9b8c-e0b63416c6d0.png)

**Comment by richardquint** [comment]
Downloaded the latest version, still the same behaviour as shown above.

**Comment by mzur** [comment]
Please show the output of `journalctl /usr/bin/gnome-shell | tail -n 50` after a restart of GNOME shell.

**Comment by richardquint** [comment]
Here's the output of `journalctl /usr/bin/gnome-shell | tail -n 50` first before enabling Workspace matrix and then after enabling it and doing ALT+F2 r.
[report.txt](https://github.com/mzur/gnome-shell-wsmatrix/files/3776145/report.txt)

**Comment by mzur** [comment]
I see. The log does not indicate any error of this extension. In your last screenshot you haven't enabled "show workspace grid in the overview". In the first screenshot it is enabled. Might this be the problem? Also we can't guarantee compatibility with other extensions that modify the same features.

**Comment by richardquint** [comment]
Thank you Martin,
I had failed to enable "show workspace grid in the overview". As you can see from the screen shots I now have the matrix displayed as I wanted.  I understand there might be a strange interaction with the Workspace Indicator extension.  In 19.10 as in 19.04 when only Workspace Indicator is enabled the indicator in the panel is the number of the active workspace enclosed in a box, and when Workspace matrix is enabled it remains the box containing the workspace number in 19.04, but in 19.10 the indicator changes to a row of boxes representing the workspaces. If I turn Workspace Indicator off while Workspace matrix remains enabled there is no indicator in the pane.

This isn't a major problem---but I liked the old way.
![Screenshot from 2019-10-28 09-38-40 Disco](https://user-images.githubusercontent.com/39503532/67700740-c006d180-f96b-11e9-93c1-dccac364456d.png)
![Screenshot from 2019-10-28 09-51-50 Eoan](https://user-images.githubusercontent.com/39503532/67700741-c006d180-f96b-11e9-83bc-83edb5571d50.png)

**Comment by ebeem** [comment]
@lautarodragan please update the wsmatrix, yours seems outdated and not compatible with 3.34.

**Comment by ebeem** [comment]
please check again as this error indicates that your version is outdated
`Oct 29 18:31:01 pop-os gnome-shell[7043]: Usage of object.actor is deprecated for WorkspaceThumbnail#012get@resource:///org/gnome/shell/ui/environment.js:242:29#012allocate@/home/tarokun/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/ThumbnailsBoxOverride.js:276:10#012vfunc_allocate@resource:///org/gnome/shell/ui/overviewControls.js:80:9#012vfunc_allocate@resource:///org/gnome/shell/ui/overviewControls.js:414:9`

uninstall the extension and install it again, seems like [GNOME extensions](https://extensions.gnome.org/extension/1485/workspace-matrix/) already updated it
try installing from it.


you can check what version you have by executing this command (assuming your extension is stored in `.local`
`cat ~/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/metadata.json | grep "shell-version"`

**Comment by richardquint** [comment]
I have tried both the current version from GitHub and from extensions.gnome.org. They are the same except for the metadata.json file.  It is for shell version 3.34.  BTW, the command `cat ~/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/metadata.json | grep "shell-version"` doesn't work as expected with the extensions.gnome.org version since the "3.34"  is on the next line.

**Comment by lautarodragan** [comment]
@ebeem you're right, sorry for the false alarm! updated and works perfectly as always.

**Comment by ebeem** [comment]
@richardquint sorry, my previous messages were not for your problem
your problem doesn't seem to be related to this extension, it seems related to the way `workspace-indicator` handles horizontal workspaces. seems like GNOME 3.34 affected the way `workspace-indicator` displays workspaces with the new introduced horizontal workspaces, I am not sure if this is an expected behavior or not, but you probably want to create an issue in `workspace-indicator` for this problem.

**Comment by ebeem** [comment]
I am closing this for now as [this comment](https://github.com/mzur/gnome-shell-wsmatrix/issues/71#issuecomment-546887923) solves it. Please feel free to open a new issue if there is another problem with the extension.
Let us know if you think this issue was not resolved and we should reopen it.
