### ISSUE TITLE
“Show workspace grid in the overview” no longer working on Fedora 31

### ISSUE THREAD

**Issue by not-a-lot** [mzur/gnome-shell-wsmatrix#72]
Hi, I upgraded from Fedora 30 to Fedora 31 yesterday, and now, my 3 × 3 grid does not appear anymore in the side panel in the Activities overview. The side panel is just a dark grey rectangle with nothing inside. I upgraded the extension to the newest release, too, and the option “Show workspace grid in the overview” is enabled.

Switching workspaces and moving windows between them show the grid in the middle of the screen, and these features are working fine.

Could this be due to the fact that I’m using the nvidia proprietary driver with X11 still ? (I don’t like it and my next card will be an AMD, but for the time being, I have to stay with that)

Here is the output of `journalctl /usr/bin/gnome-shell | tail -n 50` after a restart of GNOME shell :
[log.txt](https://github.com/mzur/gnome-shell-wsmatrix/files/3793803/log.txt)

**Comment by ebeem** [comment]
it's not so clear, please provide more log
may be tail 150 or 200

**Comment by not-a-lot** [comment]
Thank you for your answer, ebeem ! I completely removed and reinstalled the extension, and now it works again ! One thing that isn’t like it was in Fedora 30 is that when I enter the Activities overview, the grid in the side panel has a slight “expanding” animation, which is a little distracting. Is that a new feature of the extension or just something with the new version of GNOME ? And I think that the grid used to be vertically centered in the side panel, but that doesn’t matter too much

**Comment by ebeem** [comment]
I think I fixed this part, we commented the animation code before the release of V3 of `WSMatrix` (`GNOME 3.34`), now it's implemented. (if I understand what do you mean)

**Comment by ebeem** [comment]
ok, I can see what do you mean now
seems like you're right about the animation issue in your last comment, the expanding animation is not supposed to occur, I think there is an error in size calculation of the thumbnails.

Please open a new issue for this so we continue monitoring it.
