### ISSUE TITLE
No wraparound but still free movement?

### ISSUE THREAD

**Issue by dodiak** [mzur/gnome-shell-wsmatrix#80]
Hi folks,

I am trying to do not have any wraparound but freely move within the matrix. It does not work for me. When I set No wraparound then I can move just as on 1D list. So left/right no up/down. What is the trick? Or is there a problem? 3.14
thanks

Jozef

**Comment by mzur** [comment]
Is 3.14 the GNOME version that you use? This extension does not support GNOME 3.14 and it probably won't work correctly.

**Comment by dodiak** [comment]
Here is my installation. What is the version which does work correctly? Thanks.
ii  gnome                                  1:3.30+2                                   amd64        Full GNOME Desktop Environment, with extra components
ii  gnome-accessibility-themes             3.28-1                                     all          High Contrast GTK+ 2 theme and icons
ii  gnome-backgrounds                      3.34.0-1                                   all          Set of backgrounds packaged with the GNOME desktop
ii  gnome-bluetooth                        3.34.0-1                                   amd64        GNOME Bluetooth tools
ii  gnome-calculator                       3.34.1-1                                   amd64        GNOME desktop calculator
ii  gnome-calendar                         3.34.2-1+b1                                amd64        Calendar application for GNOME
ii  gnome-characters                       3.32.1-2                                   amd64        character map application
ii  gnome-chess                            1:3.34.0-1                                 amd64        simple chess game
ii  gnome-clocks                           3.34.0-1+b2                                amd64        Simple GNOME app with stopwatch, timer, and world clock support
ii  gnome-color-manager                    3.32.0-2                                   amd64        Color management integration for the GNOME desktop environment
ii  gnome-contacts                         3.34-2                                     amd64        Contacts manager for GNOME
ii  gnome-control-center                   1:3.34.1-1                                 amd64        utilities to configure the GNOME desktop
ii  gnome-control-center-data              1:3.34.1-1                                 all          configuration applets for GNOME - data files
ii  gnome-core                             1:3.30+2                                   amd64        GNOME Desktop Environment -- essential components
ii  gnome-desktop3-data                    3.34.1-1                                   all          Common files for GNOME desktop apps
ii  gnome-disk-utility                     3.34.0-2                                   amd64        manage and configure disk drives and media
ii  gnome-documents                        3.34.0-1                                   amd64        Document manager for GNOME
ii  gnome-font-viewer                      3.34.0-1+b1                                amd64        font viewer for GNOME
ii  gnome-games                            1:3.30+2                                   all          games for the GNOME desktop
ii  gnome-getting-started-docs             3.34.0-2                                   all          Help a new user get started in GNOME
ii  gnome-icon-theme                       3.12.0-3                                   all          GNOME Desktop icon theme
ii  gnome-keyring                          3.34.0-1                                   amd64        GNOME keyring services (daemon and tools)
ii  gnome-keyring-pkcs11:amd64             3.34.0-1                                   amd64        GNOME keyring module for the PKCS#11 module loading library
ii  gnome-klotski                          1:3.34.0-1                                 amd64        Klotski puzzle game for GNOME
ii  gnome-logs                             3.34.0-1                                   amd64        viewer for the systemd journal
ii  gnome-mahjongg                         1:3.34.0-1                                 amd64        classic Eastern tile game for GNOME
ii  gnome-maps                             3.34.1-1                                   amd64        map application for GNOME
ii  gnome-menus                            3.32.0-1                                   amd64        GNOME implementation of the freedesktop menu specification
ii  gnome-mime-data                        2.18.0-2                                   all          base MIME and Application database for GNOME.
ii  gnome-mines                            1:3.34.0-1                                 amd64        popular minesweeper puzzle game for GNOME
ii  gnome-music                            3.32.2-1                                   amd64        Music is the new GNOME music playing application
ii  gnome-nibbles                          1:3.34.1-1                                 amd64        snake game, up to four players
ii  gnome-online-accounts                  3.34.1-1                                   amd64        service to manage online accounts for the GNOME desktop
ii  gnome-online-miners                    3.34.0-1                                   amd64        Crawls through your online content
ii  gnome-orca                             3.34.0-2                                   all          Scriptable screen reader - transitional package
ii  gnome-pkg-tools                        0.21.2                                     all          Tools for the Debian GNOME Packaging Team
ii  gnome-robots                           1:3.34.0-1                                 amd64        improved old BSD robots game
ii  gnome-screenshot                       3.34.0-1                                   amd64        screenshot application for GNOME
ii  gnome-session                          3.34.1-1                                   all          GNOME Session Manager - GNOME 3 session
ii  gnome-session-bin                      3.34.1-1                                   amd64        GNOME Session Manager - Minimal runtime
ii  gnome-session-common                   3.34.1-1                                   all          GNOME Session Manager - common files
ii  gnome-settings-daemon                  3.34.1-1+b1                                amd64        daemon handling the GNOME session settings
ii  gnome-settings-daemon-common           3.34.1-1                                   all          daemon handling the GNOME session settings - common files
ii  gnome-shell                            3.34.1+git20191024-1                       amd64        graphical shell for the GNOME desktop
ii  gnome-shell-common                     3.34.1+git20191024-1                       all          common files for the GNOME graphical shell
ii  gnome-shell-extensions                 3.34.1-2                                   all          Extensions to extend functionality of GNOME Shell
ii  gnome-software                         3.30.6-5+b1                                amd64        Software Center for GNOME
ii  gnome-software-common                  3.30.6-5                                   all          Software Center for GNOME (common files)
ii  gnome-sound-recorder                   3.34.0-1                                   all          simple and modern sound recorder for GNOME
ii  gnome-sudoku                           1:3.34.1-1                                 amd64        Sudoku puzzle game for GNOME
ii  gnome-sushi                            3.34.0-2                                   amd64        sushi is a quick previewer for nautilus
ii  gnome-system-monitor                   3.32.1-2                                   amd64        Process viewer and system resource monitor for GNOME
ii  gnome-taquin                           3.34.1-1                                   amd64        game to move tiles so that they reach their places
ii  gnome-terminal                         3.34.2-1                                   amd64        GNOME terminal emulator application
ii  gnome-terminal-data                    3.34.2-1                                   all          Data files for the GNOME terminal emulator
ii  gnome-tetravex                         1:3.34.1-1                                 amd64        put tiles on a board and match their edges together
ii  gnome-themes-extra:amd64               3.28-1                                     amd64        Adwaita GTK+ 2 theme — engine
ii  gnome-themes-extra-data                3.28-1                                     all          Adwaita GTK+ 2 theme — common files
ii  gnome-todo                             3.28.1-5                                   amd64        minimalistic personal task manager designed to fit GNOME desktop
ii  gnome-todo-common                      3.28.1-5                                   all          common files for GNOME To Do
ii  gnome-tweaks                           3.34.0-2                                   all          tool to adjust advanced configuration settings for GNOME
ii  gnome-user-docs                        3.34.0-2                                   all          GNOME user docs
ii  gnome-user-share                       3.34.0-2                                   amd64        User level public file sharing via WebDAV
ii  gnome-video-effects                    0.5.0-1                                    all          Collection of GStreamer effects
ii  gnome-weather                          3.34.0-1                                   all          access current conditions and forecasts
ii  libgnome-autoar-0-0:amd64              0.2.3-2                                    amd64        Archives integration support for GNOME
ii  libgnome-autoar-gtk-0-0:amd64          0.2.3-2                                    amd64        GTK+ widgets for the GNOME Autoar library
ii  libgnome-bluetooth13:amd64             3.34.0-1                                   amd64        GNOME Bluetooth tools - support library
ii  libgnome-desktop-3-17:amd64            3.30.2.1-2                                 amd64        Utility library for loading .desktop files - runtime files
ii  libgnome-desktop-3-18:amd64            3.34.1-1                                   amd64        Utility library for loading .desktop files - runtime files
ii  libgnome-desktop-3-dev:amd64           3.34.1-1                                   amd64        Utility library for loading .desktop files - development files
ii  libgnome-games-support-1-3:amd64       1.4.4-1                                    amd64        library for common functions of GNOME games
ii  libgnome-games-support-common          1.4.4-1                                    all          library for common functions of GNOME games (common files)
ii  libgnome-menu-3-0:amd64                3.32.0-1                                   amd64        GNOME implementation of the freedesktop menu specification
ii  libgnome-todo                          3.28.1-5                                   amd64        library data for GNOME To Do
rc  libgnome2-common                       2.32.1-5                                   all          The GNOME library - common files
ii  libgnomekbd-common                     3.26.1-1                                   all          GNOME library to manage keyboard configuration - common files
ii  libgnomekbd8:amd64                     3.26.1-1                                   amd64        GNOME library to manage keyboard configuration - shared library
ii  libgnomevfs2-0:amd64                   1:2.24.4-6.1+b2                            amd64        GNOME Virtual File System (runtime libraries)
ii  libgnomevfs2-common                    1:2.24.4-6.1                               all          GNOME Virtual File System (common files)
ii  libgnomevfs2-extra:amd64               1:2.24.4-6.1+b2                            amd64        GNOME Virtual File System (extra modules)

**Comment by mzur** [comment]
This looks like you've got GNOME 3.30. This version suffers from a bug in Mutter (see [here](https://github.com/mzur/gnome-shell-wsmatrix/issues/2#issuecomment-435074560)). You can update GNOME or patch your Mutter version manually.

**Comment by dodiak** [comment]
Thanks, I will try ;)
