### ISSUE TITLE
[Feature Request] Make an option to disable overview keybinding.

### ISSUE THREAD

**Issue by kevinhwang91** [mzur/gnome-shell-wsmatrix#83]
It conflict with my custom keybinding, annoy me very much!

**Comment by mzur** [comment]
Keybindings for this extension should be configured with the `gsettings set` command ([example](https://github.com/mzur/gnome-shell-wsmatrix/issues/62#issuecomment-539555329)). I'm sure you can use the command to set the keybinding to nothing.

**Comment by kevinhwang91** [comment]
It works after I copy the gschema.xml to glib-2.0/schema/ and compile. Without this action `gsettings` can't find  `org.gnome.shell.extensions.wsmatrix-keybindings workspace-overview-toggle`. 
I suggest adding a GUI option to disable it easily.
