### ISSUE TITLE
Error loading extension in Ubuntu 19.10

### ISSUE THREAD

**Issue by JorgeHernansanz** [mzur/gnome-shell-wsmatrix#85]
HI there!

I'm experiencing problems to switch the MW extension on. In particular, it shows me the next warning:

![Screenshot from 2020-01-06 09-29-48](https://user-images.githubusercontent.com/38537513/71808551-5e9b6700-306e-11ea-8126-ba73840c57ec.png).

Rebooting or reinstalling it from the Ubuntu store doesn't fix it.

**Comment by mzur** [comment]
Please show the output of `journalctl /usr/bin/gnome-shell | tail -n 100` after a restart.

**Comment by JorgeHernansanz** [comment]
jorge@Ubuntium:~$ journalctl /usr/bin/gnome-shell | tail -n 100
ene 06 10:35:11 Ubuntium gnome-shell[1767]: [AppIndicatorSupport-FATAL] unable to update overlay icon
ene 06 10:35:11 Ubuntium gnome-shell[1767]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
ene 06 10:35:11 Ubuntium gnome-shell[1767]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
ene 06 10:35:11 Ubuntium gnome-shell[1767]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
ene 06 10:35:11 Ubuntium gnome-shell[1767]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
ene 06 10:35:11 Ubuntium gnome-shell[1767]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
ene 06 10:35:11 Ubuntium gnome-shell[1767]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
ene 06 10:35:11 Ubuntium gnome-shell[1767]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
ene 06 10:35:11 Ubuntium gnome-shell[1767]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
ene 06 10:35:11 Ubuntium gnome-shell[1767]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
ene 06 10:41:55 Ubuntium firefox.desktop[1767]: [Parent 3689, Gecko_IOThread] WARNING: pipe error (128): Connection reset by peer: file /build/firefox-kECWsf/firefox-71.0+build5/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
ene 06 10:41:55 Ubuntium firefox.desktop[1767]: [Parent 3689, Gecko_IOThread] WARNING: pipe error (246): Connection reset by peer: file /build/firefox-kECWsf/firefox-71.0+build5/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
ene 06 10:41:55 Ubuntium firefox.desktop[1767]: [Parent 3689, Gecko_IOThread] WARNING: pipe error (175): Connection reset by peer: file /build/firefox-kECWsf/firefox-71.0+build5/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
ene 06 10:42:03 Ubuntium gnome-shell[1767]: gnome-shell: Fatal IO error 0 (Success) on X server :0.
-- Reboot --
ene 06 10:43:33 Ubuntium gnome-shell[1172]: Failed to obtain high priority context
ene 06 10:43:33 Ubuntium gnome-shell[1172]: Failed to obtain high priority context
ene 06 10:43:41 Ubuntium gnome-shell[1172]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
ene 06 10:43:41 Ubuntium gnome-shell[1172]: Will monitor session c1
ene 06 10:43:44 Ubuntium gnome-shell[1172]: Getting invalid resource scale property
ene 06 10:43:44 Ubuntium gnome-shell[1172]: ibus_bus_hello: assertion 'ibus_bus_is_connected (bus)' failed
ene 06 10:43:44 Ubuntium gnome-shell[1172]: Error while sending AddMatch() message: La conexión está cerrada
ene 06 10:43:44 Ubuntium gnome-shell[1172]: ibus_bus_call_async: assertion 'ibus_bus_is_connected (bus)' failed
ene 06 10:43:44 Ubuntium gnome-shell[1172]: ibus_bus_call_async: assertion 'ibus_bus_is_connected (bus)' failed
ene 06 10:43:44 Ubuntium gnome-shell[1172]: Error setting property 'Powered' on interface org.bluez.Adapter1: GDBus.Error:org.bluez.Error.Blocked: Blocked through rfkill (g-io-error-quark, 36)
ene 06 10:43:44 Ubuntium gnome-shell[1172]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
ene 06 10:43:45 Ubuntium gnome-shell[1172]: JS WARNING: [resource:///org/gnome/shell/ui/windowManager.js 1640]: reference to undefined property "MetaWindowXwayland"
ene 06 10:43:46 Ubuntium gnome-shell[1172]: Registering session with GDM
ene 06 10:44:00 Ubuntium gnome-shell[1728]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
ene 06 10:44:00 Ubuntium gnome-shell[1728]: Will monitor session 2
ene 06 10:44:00 Ubuntium gnome-shell[1728]: current session already has an ibus-daemon.
ene 06 10:44:01 Ubuntium gnome-shell[1728]: Telepathy is not available, chat integration will be disabled.
ene 06 10:44:02 Ubuntium gnome-shell[1728]: Usage of object.actor is deprecated for Freon_FreonMenuButton
                                            get@resource:///org/gnome/shell/ui/environment.js:249:29
                                            _init@/home/jorge/.local/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:96:9
                                            enable@/home/jorge/.local/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/extension.js:637:17
                                            _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:132:13
                                            loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:264:21
                                            _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:482:13
                                            collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                            _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:457:9
                                            _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:491:13
                                            _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:522:13
                                            init@resource:///org/gnome/shell/ui/extensionSystem.js:32:9
                                            _initializeUI@resource:///org/gnome/shell/ui/main.js:245:5
                                            start@resource:///org/gnome/shell/ui/main.js:141:5
                                            @<main>:1:31
ene 06 10:44:03 Ubuntium gnome-shell[1728]: JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1090]: unreachable code after return statement
ene 06 10:44:03 Ubuntium gnome-shell[1728]: JS ERROR: Extension ubuntu-dock@ubuntu.com: Error: Type name Gjs_DashToDock_WindowPreviewMenuItem is already registered
                                            _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/overrides/GObject.js:385:24
                                            registerClass@resource:///org/gnome/gjs/modules/overrides/GObject.js:94:12
                                            @/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/windowPreview.js:313:29
                                            @/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js:33:7
                                            @/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/dash.js:26:7
                                            @/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js:29:7
                                            @/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/extension.js:6:7
                                            _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:331:13
                                            loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:261:22
                                            _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:482:13
                                            collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                            _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:457:9
                                            _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:491:13
                                            _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:522:13
                                            init@resource:///org/gnome/shell/ui/extensionSystem.js:32:9
                                            _initializeUI@resource:///org/gnome/shell/ui/main.js:245:5
                                            start@resource:///org/gnome/shell/ui/main.js:141:5
                                            @<main>:1:31
ene 06 10:44:04 Ubuntium gnome-shell[1728]: Error setting property 'Powered' on interface org.bluez.Adapter1: GDBus.Error:org.bluez.Error.Blocked: Blocked through rfkill (g-io-error-quark, 36)
ene 06 10:44:04 Ubuntium gnome-shell[1172]: Failed to CRTC gamma: drmModeCrtcSetGamma on CRTC 48 failed: Permiso denegado
ene 06 10:44:04 Ubuntium gnome-shell[1728]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
ene 06 10:44:05 Ubuntium gnome-shell[1172]: Failed to CRTC gamma: drmModeCrtcSetGamma on CRTC 48 failed: Permiso denegado
ene 06 10:44:06 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
ene 06 10:44:06 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
ene 06 10:44:06 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
ene 06 10:44:06 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
ene 06 10:44:06 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
ene 06 10:44:06 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
ene 06 10:44:06 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
ene 06 10:44:06 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
ene 06 10:44:06 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
ene 06 10:44:06 Ubuntium gnome-shell[1728]: GNOME Shell started at Mon Jan 06 2020 10:44:02 GMT+0100 (CET)
ene 06 10:44:06 Ubuntium gnome-shell[1728]: Registering session with GDM
ene 06 10:44:07 Ubuntium gnome-shell[1172]: Connection to xwayland lost
ene 06 10:45:14 Ubuntium gnome-shell[1728]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.90/org/ayatana/NotificationItem/software_update_available
ene 06 10:45:14 Ubuntium gnome-shell[1728]: [AppIndicatorSupport-FATAL] unable to update overlay icon
ene 06 10:45:14 Ubuntium gnome-shell[1728]: [AppIndicatorSupport-FATAL] unable to update overlay icon
ene 06 10:45:15 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
ene 06 10:45:15 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
ene 06 10:45:15 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
ene 06 10:45:15 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
ene 06 10:45:15 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
ene 06 10:45:15 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
ene 06 10:45:15 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
ene 06 10:45:15 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
ene 06 10:45:15 Ubuntium gnome-shell[1728]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
ene 06 10:45:17 Ubuntium gnome-shell[1728]: # _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
ene 06 10:45:17 Ubuntium gnome-shell[1728]: # _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
ene 06 10:45:17 Ubuntium gnome-shell[1728]: # watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
ene 06 10:45:17 Ubuntium gnome-shell[1728]: # unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
ene 06 10:45:17 Ubuntium gnome-shell[1728]: # watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)

**Comment by mzur** [comment]
There is no error related to this extension. Is it enabled?

**Comment by JorgeHernansanz** [comment]
Now that I look yes. After enabling another extension called 'Dash to dock' and disabling 'Ubuntu dock', now works fine. Moreover, the thumbnails are displayed correctly. It seems there's no more errors.
