### ISSUE TITLE
Dual Monitor bug

### ISSUE THREAD

**Issue by AKALuffy** [mzur/gnome-shell-wsmatrix#86]
Hi,

I'm on ubuntu 19.10 with gnome 3.34.1.

I have 3 monitor and manage matrix like this : 

![image](https://user-images.githubusercontent.com/23058479/72147577-1dbd8e00-339f-11ea-91fa-fadfb64446c3.png)

Matrix works but when i switch with ctrl + alt + row : 

- Only main monitor can have different app on each workspace
- 2 others monitor got fix workspace

If i got 3 monitor i want that each got one workspace not only main monitor, is that possible ?

**Comment by mzur** [comment]
This has nothing to do with the Workspace Matrix extension. You can configure your monitors using the GNOME Tweaks tool. Select "Workspaces" and then activate "Workspaces span displays" to get what you want.

**Comment by AKALuffy** [comment]
My bad,  you are right, it's work perfectly now. Thanks
