### ISSUE TITLE
Provide a way to change the Show Workspace Selector hotkey.

### ISSUE THREAD

**Issue by noel-yap** [mzur/gnome-shell-wsmatrix#87]
If there's already a way to do this, please document it.

**Comment by mzur** [comment]
You can find a link to an [example](https://github.com/mzur/gnome-shell-wsmatrix/issues/62#issuecomment-539555329) in the [known issues](https://github.com/mzur/gnome-shell-wsmatrix#known-issues).

**Comment by mzur** [comment]
There is now an extra [wiki page](https://github.com/mzur/gnome-shell-wsmatrix/wiki/Custom-keyboard-shortcuts) for that.
