### ISSUE TITLE
how to change timeout - ubuntu 18.04

### ISSUE THREAD

**Issue by 1robroos** [mzur/gnome-shell-wsmatrix#89]
With `ctrl-alt-arrow-up` or `arrow-down` I see the workspace-matrix, but for a very short amount of time. How can I extend that time?

**Comment by mzur** [comment]
This is possible in the settings of a newer version of this extension (for GNOME 3.32). The feature hasn't been backported. It should work once you upgrade to the upcoming 20.04 LTS release.

**Comment by mzur** [comment]
Please reopen if this is still relevant.
