### ISSUE TITLE
Missing thumbnails on Gnome 3.32

### ISSUE THREAD

**Issue by enachesilviu** [mzur/gnome-shell-wsmatrix#9]
Running Arch with Gnome 3.32

Instead of the workspace thumbnails I get a huge rectangle.

![ezgif-5-9f8dfc45edee](https://user-images.githubusercontent.com/7116229/54586949-3bdc8b00-4a27-11e9-9d95-7d6a887e402e.gif)

**Comment by mzur** [comment]
Please try the [v2.0.0](https://github.com/mzur/gnome-shell-wsmatrix/releases/tag/v2.0.0) release. This has not been published on extensions.gnome.org yet.

**Comment by enachesilviu** [comment]
Works great, thanks. I wish I knew how to check before disturbing, I'll close this issue.
