### ISSUE TITLE
Error loading this extension in Gnome 3.34.

### ISSUE THREAD

**Issue by Quip11** [mzur/gnome-shell-wsmatrix#90]
It appears to work anyway, at least until I walk away and the shell suspends and resumes.

[wsmatrix.log](https://github.com/mzur/gnome-shell-wsmatrix/files/4142821/wsmatrix.log)

**Comment by Quip11** [comment]
diff --git a/wsmatrix@martin.zurowietz.de/ThumbnailsBoxOverride.js b/wsmatrix@martin.zurowietz.de/ThumbnailsBoxOverride.js
index 60f945a..93ab919 100644
--- a/wsmatrix@martin.zurowietz.de/ThumbnailsBoxOverride.js
+++ b/wsmatrix@martin.zurowietz.de/ThumbnailsBoxOverride.js
@@ -38,7 +38,7 @@ var ThumbnailsBoxOverride = class {
       this.thumbnailsBox.getColumns = this.getColumns.bind(this);
 
       this.thumbnailsBox._indicatorX = 0;
-      Object.defineProperty(this.thumbnailsBox, "indicator_x", {
+      Object.defineProperty(this.thumbnailsBox, "_indicatorX", {
          // eslint-disable-next-line camelcase
          set: function (indicatorX) {
             if (this._indicatorX == indicatorX)

**Comment by mzur** [comment]
Is the diff a fix that makes the error disappear?

**Comment by Quip11** [comment]
Yes, it's working great.

**Comment by Quip11** [comment]
How did you edit my comment so that it shows up as a diff?  I'd like to know for next time I post a diff on Github.

**Comment by mzur** [comment]
I put it in a code block:
<pre>
```diff
your diff here
```
</pre>
You can see it when you edit your own comment from above.

**Comment by ebeem** [comment]
@Quip11 
I think this issue is the same as this one reported [here](https://github.com/mzur/gnome-shell-wsmatrix/issues/75)
can you please check the last provided solution?
according to my understanding, your code will not fix the problem and it will end up showing up at one point.
This function is not so important as it's used for animation.

**Comment by Quip11** [comment]
Yes, this is a duplicate of #75.  I'll try the last provided solution there.
