### ISSUE TITLE
Won't load in gnome-shell 3.34 (JS ERROR: InternalError: too much recursion)

### ISSUE THREAD

**Issue by wziard** [mzur/gnome-shell-wsmatrix#91]
The log contains the following error message:

```
feb 05 14:39:32 username-dualgpu gnome-shell[20206]: JS ERROR: InternalError: too much recursion
                                                    allocate@/home/username/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/ThumbnailsBoxOverride.js:166:7
                                                    allocate@/home/username/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/ThumbnailsBoxOverride.js:166:7
                                                    allocate@/home/username/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/ThumbnailsBoxOverride.js:166:7
<lots of repetitions of this line snipped>
```

**Comment by mzur** [comment]
When does this occur? Are there any specific steps to reproduce this?

**Comment by wziard** [comment]
Ubuntu 19.10 no special steps. 

I'll try to find out what other extensions are loaded, but it's on my work machine and I'm not there atm.

**Comment by JasonDD** [comment]
I have this same issue on 20.04

I'm happy to help debug and assist in any way, but will need guidance on what info and how to get it :)

**Comment by ebeem** [comment]
how often does it happen? any special steps to reproduce?
the distro used can help test on the environment
also a list of installed extensions and [full log](https://github.com/mzur/gnome-shell-wsmatrix#contributing) will be helpful.

**Comment by JasonDD** [comment]
Thank you ebeem.

As it so happens, I just had a standard Ubuntu update for the 20.04 (which are coming thick and fast now) and it has resolved itself.

If this error comes back, I will attach a full log, but fingers crossed, your excellent utility will persist through reboots etc :)

thank you

**Comment by JasonDD** [comment]
Alas, a reboot later and it's not working again. 

Here is a snippet from the journalctl, which I would be happy to provide the full version of, if this doesn't help. (It's big at 183Mb)

jason@JasonNix:~$ journalctl --no-pager /usr/bin/gnome-shell > gnome-shell.journalctl
jason@JasonNix:~$ du -h gnome-shell.journalctl 
183M	gnome-shell.journalctl
jason@JasonNix:~$ tail gnome-shell.journalctl 
Mar 02 22:29:37 JasonNix gnome-shell[3556]: JS ERROR: Extension wsmatrix@martin.zurowietz.de: TypeError: Main.overview._controls is undefined
                                            _activateOverride@/home/jason/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js:78:11
                                            _handleShowOverviewGridChanged@/home/jason/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js:68:10
                                            OverviewOverride<@/home/jason/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/OverviewOverride.js:21:7
                                            WsMatrixExtension@/home/jason/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:13:31
                                            enable@/home/jason/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/extension.js:25:15
                                            _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:161:13
                                            loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:312:21
                                            callback@resource:///org/gnome/shell/ui/extensionDownloader.js:216:17
                                            gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13

**Comment by ebeem** [comment]
@JasonDD this seems to be a different problem than `JS ERROR: InternalError: too much recursion`
yours seems to be caused by gnome-shell crashing somehow or losing its `Main.overview`
do you have any other extensions installed? especially ones that modify the overview, these will most likely cause such an issue.

do you know any action that we can take to reproduce? it seems like this error occurred when your system woke up from sleep/suspend/lock am I right? this issue will probably be caused by some other factors (not WSMatrix), but we need to investigate more to confirm it.

please feel free to open a new issue if you think yours is not related to #91

**Comment by JasonDD** [comment]
Thanks Ebeem.

I apologise for my lack of knowledge on this. I'll open another issue.

**Comment by ebeem** [comment]
@JasonDD seems like the issue you mentioned was related to gnome 3.36 update
in case you updated your gnome and you received that error, then try the PR #97

**Comment by ebeem** [comment]
@wziard any news about this?
does it still happen? any full log or steps to produce can be provided?

**Comment by wziard** [comment]
This happens on my work machine at the office. But due to the corona situation I currently work from home.

I plan to update my laptop to ubuntu 20.04 in the near future. I'll let you know if the problem appears there as well.

As soon as I'm in the office once again, I'll try if an update fixes it there. That could be a while though, because I live in a different city and public transport is limited atm.

**Comment by mzur** [comment]
Please reopen if this is still relevant (and still affects GNOME >=3.36).
