### ISSUE TITLE
Gnome 3.36 - Won't Load - Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?

### ISSUE THREAD

**Issue by ElijahLynn** [mzur/gnome-shell-wsmatrix#98]
After Gnome 3.36 update yesterday I get the below error:

> Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
> 
> Stack trace:
>   Settings@/home/elijah/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/Settings.js:23:5
>   buildPrefsWidget@/home/elijah/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/prefs.js:144:19
>   _showPrefs@resource:///org/gnome/shell/extensionPrefs/main.js:174:38
>   _extensionsLoaded@resource:///org/gnome/shell/extensionPrefs/main.js:467:18
>   _scanExtensions/<@resource:///org/gnome/shell/extensionPrefs/main.js:418:18
>   asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
>   main@resource:///org/gnome/shell/extensionPrefs/main.js:762:23
>   @<main>:1:48

![image](https://user-images.githubusercontent.com/1504756/76358772-41398200-62d7-11ea-8c3b-79e8b0a61791.png)

**Comment by ElijahLynn** [comment]
Hrm, actually it appears the update yesterday did _not_ update to 3.36 but instead from 3.34 to 3.35.91.

**Comment by ElijahLynn** [comment]
Checking for latest updates now (Arch).

**Comment by ebeem** [comment]
is it related to this #52? 
and if you're running 3.36 try PR #97 for now

**Comment by ElijahLynn** [comment]
K, just updated from 3.35.91 to 3.36.0 and same error. I'll try #97.

**Comment by ElijahLynn** [comment]
I uninstalled extension, followed manual install here https://github.com/mzur/gnome-shell-wsmatrix#developing on master and it worked nicely, as it did before. I also checked out #97 and restarted Gnome and it also works the same. 

Closing as this will work for now and looks like the next release will have this resolved.
